\documentclass[a4paper]{report}

\usepackage[T1]{fontenc}
\usepackage[polish]{babel}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{graphicx}
\usepackage{setspace}
\usepackage{savesym}
\savesymbol{arc}
\usepackage{color}
\usepackage{xcolor}
\usepackage{pict2e}
\usepackage{epstopdf}
\usepackage{geometry}
\usepackage{enumerate}
\usepackage{multicol}
\usepackage[strict]{changepage}
\usepackage{titlesec}
\usepackage{etoolbox}
\usepackage{tocloft}
\usepackage{imakeidx}
\usepackage{ifthen}
\usepackage{fancyhdr}
\usepackage{varwidth}

\setcounter{secnumdepth}{0}
\setcounter{tocdepth}{1}

\newgeometry{tmargin=2cm, bmargin=2cm, lmargin=1.1cm, rmargin=1.1cm}{}{}

\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot[C]{--~\thepage~--}

\titleformat{\section}[hang]{\normalfont\bfseries\LARGE\centering}{\thesection}{0pt}{}{}
\titleformat{\subsection}[hang]{\normalfont\itshape\bfseries\Large\centering\color{gray}}{\thesubsection}{0pt}{\Large}
\titlespacing*{\section}{0pt}{\baselineskip}{0.1\baselineskip}
\titlespacing*{\subsection}{0pt}{0.1\baselineskip}{2\baselineskip}

\newenvironment{song1}[2]{
     \section{\MakeUppercase{#1}}
	\subsection{\MakeUppercase{#2}}
	\Large
	\index[autorzy]{{#2}!{#1}}
	\index[piosenki]{#1}
    \begin{center}
    	\begin{varwidth}{\linewidth}}{
    	\end{varwidth}
    \end{center}
	\newpage
    }
    
\newenvironment{song1kilku}[4]{
	\section{\MakeUppercase{#1}}
	\ifthenelse{\not\equal{#4}{}}{\subsection{\MakeUppercase{#2} \& \MakeUppercase{#3} \& \MakeUppercase{#4}}
								  \index[piosenki]{#1}\index[autorzy]{{#2}!{#1}}\index[autorzy]{{#3}!{#1}}\index[autorzy]{{#4}!{#1}}}{
	\ifthenelse{\not\equal{#3}{}}{\subsection{\MakeUppercase{#2} \& \MakeUppercase{#3}}
								  \index[piosenki]{#1}\index[autorzy]{{#2}!{#1}}\index[autorzy]{{#3}!{#1}}}{
	\ifthenelse{\not\equal{#2}{}}{\subsection{\MakeUppercase{#2}}
								  \index[piosenki]{#1}\index[autorzy]{{#2}!{#1}}}{}}}
	\Large	
	\begin{center}
		\begin{varwidth}{\linewidth}}{
		\end{varwidth}
	\end{center}
	\newpage
    }

\newenvironment{song2kilku}[4]{	
	\begin{multicols*}{2}[
		\section{\MakeUppercase{#1}}
		\ifthenelse{\not\equal{#4}{}}{\subsection{\MakeUppercase{#2} \& \MakeUppercase{#3} \& \MakeUppercase{#4}}
									  \index[piosenki]{#1}\index[autorzy]{{#2}!{#1}}\index[autorzy]{{#3}!{#1}}\index[autorzy]{{#4}!{#1}}}{
		\ifthenelse{\not\equal{#3}{}}{\subsection{\MakeUppercase{#2} \& \MakeUppercase{#3}}
									  \index[piosenki]{#1}\index[autorzy]{{#2}!{#1}}\index[autorzy]{{#3}!{#1}}}{
		\ifthenelse{\not\equal{#2}{}}{\subsection{\MakeUppercase{#2}}
									  \index[piosenki]{#1}\index[autorzy]{{#2}!{#1}}}{}}}]
	     \Large
          \begin{center}
               \begin{varwidth}{\columnwidth}}{
               \end{varwidth}
          \end{center}
     \end{multicols*}
	\newpage
    }

\newenvironment{song2}[2]{	
	\begin{multicols*}{2}[
		\section{\MakeUppercase{#1}}
		\subsection{\MakeUppercase{#2}}]
		\Large
		\index[autorzy]{{#2}!{#1}}
		\index[piosenki]{#1}
          \begin{center}
               \begin{varwidth}{\columnwidth}}{
	          \end{varwidth}
          \end{center}
     \end{multicols*}
	\newpage
    }
    
\indexsetup{othercode=\small}
\makeindex[name=piosenki, title=INDEKS UTWORÓW]
\makeindex[name=autorzy, title=INDEKS WYKONAWCÓW]

\begin{document}
\SweaveOpts{concordance=TRUE}

%%%%%%%%%%%%%%%%%%%%%%%%%%%% To trzeba wklejać przy łamaniu kolumny w song2 i song2kilku: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \end{varwidth}
% \end{center}
% \columnbreak
% \begin{center}
% \begin{varwidth}{\columnwidth}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% POCZĄTEK WPISYWANIA PIOSENEK %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\begin{song1}{Right Here Waiting}{RICHARD MARX}

Oceans apart day after day\\
And I slowly go insane\\
I hear your voice on the line\\
But it doesn't stop the pain\\
\\
If I see you next to never\\
How can we say forever\\
\\
Wherever you go\\
Whatever you do\\
I will be right here waiting for you\\
Whatever it takes\\
Or how my heart breaks\\
I will be right here waiting for you\\
\\
I took for granted, all the times\\
That I though would last somehow\\
I hear the laughter, I taste the tears\\
But I can't get near you now\\
\\
Oh, can't you see it baby\\
You've got me goin' crazy\\
\\
Wherever you go...\\
\\
I wonder how we can survive\\
This romance\\
But in the end if I'm with you\\
I'll take the chance\\
\\
Oh, can't you see it baby\\
You've got me goin' crazy\\
\\
Wherever you go...

\end{song1}

 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Without You}{Harry Nilsson}

No, I can't forget this evening\\
Or your face as you were leaving\\
But I guess that's just the way the story goes\\
You always smile but in your eyes your sorrow shows\\
Yes, it shows\\
\\
No, I can't forget tomorrow\\
When I think of all my sorrow\\
When I had you there but then I let you go\\
And now it's only fair that I should let you know\\
What you should know\\
\\
I can't live if living is without you\\
I can't live, I can't give any more\\
I can't live if living is without you\\
I can't give, I can't give any more\\
\\
No, I can't forget this evening\\
Or your face as you were leaving\\
But I guess that's just the way the story goes\\
You always smile but in your eyes your sorrow shows\\
Yes, it shows\\
\\
I can't live if living is without you\\
I can't live, I can't give anymore\\
I can't live if living is without you\\
I can't live, I can't give anymore 

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Into the West}{Annie Lennox}

Lay down\\
Your sweet and weary head\\
Night is falling\\
You have come to journey's end\\
\\
Sleep now\\
And dream of the ones who came before\\
They are calling\\
From across the distant shore\\
\\
Why do you weep?\\
What are these tears upon your face?\\
Soon you will see\\
All of your fears will pass away\\
\\
Safe in my arms\\
You're only sleeping\\
\\
What can you see\\
On the horizon?\\
Why do the white gulls call?\\
\\
Across the sea\\
A pale moon rises\\
The ships have come\\
To carry you home\\
And all will turn to silver glass\\
Lights on the water\\
All souls pass\\
\\
Hope fades\\
Into the world of night\\
Through shadows falling\\
Out of memory and time\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Don't say\\
We have come now to the end\\
White shores are calling\\
You and I will meet again\\
\\
And you'll be here in my arms\\
Just sleeping\\
\\
What can you see\\
On the horizon?\\
Why do the white gulls call?\\
\\
Across the sea\\
A pale moon rises\\
The ships have come\\
To carry you home\\
And all will turn to silver glass\\
Lights on the water\\
Grey ships pass\\
Into the West

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Poison}{Alice Cooper}

Your cruel device\\
Your blood like ice\\
One look could kill\\
My pain, your thrill\\
\\
I wanna love you but I better not touch (don’t touch)\\
I wanna hold you, but my senses tell me to stop\\
I wanna kiss you but I want it too much (too much)\\
I wanna taste you but your lips are venomous poison\\
You’re poison, running through my veins\\
You're poison, I don’t wanna break these chains\\
\\
Your mouth so hot\\
Your web, I’m caught\\
Your skin so wet\\
Black lace on sweat\\
\\
I hear you calling and it’s needles and pins (and pins)\\
I wanna hurt you just to hear you screaming my name\\
Don’t wanna touch you but you’re under my skin (deep in)\\
I wanna kiss you but your lips are venomous poison\\
You’re poison, running through my veins\\
Your poison\\
I don’t wanna break these chains\\
Poison...\\
\\
One look, could kill\\
My pain, your thrill\\
\\
I wanna love you...\\
Poison...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{This Is the Life}{Amy MacDonald}

Oh, the wind whistles down\\
The cold dark street tonight\\
And the people, they were dancing\\ 
To the music vibe\\
And the boys chase the girls\\ 
With the curls in their hair\\
While the shy tormented youth\\ 
Sit way over there\\
And the songs they get louder\\
Each one better than before\\
\\
And you're singing the songs\\
Thinking this is the life\\
And you wake up in the morning\\
And your head feels twice the size\\
Where you gonna go,\\
Where you gonna go?\\
Where you gonna sleep tonight?\\
\\
And you're singing the songs...\\
\\
So you're heading down the road\\ 
In your taxi for four\\
And your waiting\\ 
Outside Jimmy's front door\\
But nobody's in, nobody's home till four\\
So you're sitting there with nothing to do\\
Talking about Robert Riger\\ 
And his motley crew\\
And where you're gonna go?\\
Where you're gonna sleep tonight?\\
\\
And you're singing the songs...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{House of the Rising Sun}{Animals}

There is a house in New Orleans\\
They call The Rising Sun\\
And it's been the ruin of many a poor boy\\
And God, I know I'm one\\
\\
My mother was a tailor\\
Sewed my new blue jeans\\
My father was a gamblin' man\\
Down in New Orleans\\
\\
Now the only thing a gambler needs\\
Is a suitcase and a trunk\\
And the only time he'll be satisfied\\
Is when he's all drunk\\
\\
Oh, mother, tell your children\\
Not to do what I have done\\
Spend your lives in sin and misery\\
In the house of the Rising Sun\\
\\
Well I've got one foot on the platform\\
The other foot on the train\\
I'm going back to New Orleans\\
To wear that ball and chain\\
\\
Well there is a house in New Orleans\\
They call the Rising Sun\\
And it's been the ruin of many a poor boy\\
And God, I know I'm one

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Memory}{Barbra Streisand}

Midnight, not a sound from the pavement.\\
Has the moon lost her memory?\\
She is smiling alone.\\
In the lamp light the withered leaves collect at my feet.\\
And the wind begins to moan.\\
\\
Memory! All alone in the moonlight\\
I can dream of the old days,\\
Life was beautiful then.\\
I remember the time\\
I knew what happiness was,\\
Let the memory live again.\\
\\
Every street lamp seems to beat a fatalistic warning.\\
Someone mutters\\ 
And the street lamp gutters\\
And soon it will be morning.\\
\\
Daylight, I must wait for the sunrise,\\
I must think of a new life\\
And I mustn't give in.\\
When the dawn comes, tonight will be a memory too\\
And a new day will begin.\\
\\
Burnt out ends of smoky days, the still cold smell of morning.\\
A street lamp dies,\\
Another night is over,\\
Another day is dawning.\\
\\
Touch me. It's so easy to leave me\\
All alone with the memory\\
Of my days in the sun.\\
If you touch me, you'll understand what happiness is.\\
Look -- a new day has begun.

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Woman in Love}{Barbra Streisand}

Life is a moment in space,\\
When the dream is gone\\
It's a lonelier place.\\
I kiss the morning goodbye,\\
But down inside,\\ 
You know we never know why.\\
\\
The road is narrow and long\\
When eyes meet eyes\\
And the feeling is strong.\\
I turn away from the wall.\\
I stumble and fall,\\
But I give you it all.\\
\\
I am a woman in love\\
And I'd do anything\\
To get you into my world,\\
And hold you within.\\
It's a right I defend\\
Over and over again.\\
What do I do?\\
\\
With you eternally mine,\\
In love there is\\
No measure of time.\\
We planned it all at the start\\
That you and I live\\
In each others heart.\\
\\
We may be oceans away,\\
You feel my love\\
I hear what you say.\\
No truth is ever a lie.\\
I stumble and fall,\\
But I give you it all.\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
I am a woman in love\\
And I'd do anything\\
To get you into my world,\\
And hold you within.\\
It's a right I defend\\
Over and over again.\\
What do I do?\\
\\
Ooo!\\
\\
I am a woman in love\\
And I'm talkin' to you.\\
You know (I know) how you feel\\
What a woman can do.\\
It's a right I defend\\
Over and over again\\
\\
I am a woman in love\\
And I'd do anything\\
To get you into my world,\\
And hold you within.\\
It's a right I defend\\
Over and over again.\\
What do I do? 

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Surfin' U.S.A.}{Beach Boys}

If everybody had an ocean\\
Across the U.S.A.\\
Then everybody'd be surfin'\\
Like California\\
You'd seem 'em wearing their baggies\\
Huarachi sandals too\\
A bushy bushy blonde hairdo\\
Surfin' U.S.A.\\
\\
You'd catch 'em surfin' at Del Mar (Inside outside U.S.A.)\\
Ventura County line (Inside outside U.S.A.)\\
Santa Cruz and Trestles (Inside outside U.S.A.)\\
Australia's Narrabeen (Inside outside U.S.A.)\\
All over Manhattan (Inside outside U.S.A.)\\
And down Doheny way (Inside outside)\\
Everybody's gone surfin'\\
Surfin' U.S.A.\\
\\
We'll all be planning out a route\\
We're gonna take real soon\\
We're waxing down our surfboards\\
We can't wait for June\\
We'll all be gone for the summer\\
We're on safari to stay\\
Tell the teacher we're surfin'\\
Surfin' U.S.A.\\
\\
Haggerty's and Swami's (Inside outside U.S.A)\\
Pacific Palisades (Inside outside U.S.A)\\
San Onofre and Sunset (Inside outside U.S.A)\\
Redondo Beach L.A. (Inside outside U.S.A.)\\
All over La HOLLA (Inside outside U.S.A.)\\
At Waimea Bay (Inside outside)\\
Everybody's gone surfin'\\
Surfin' U.S.A.

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Stayin' Alive}{Bee Gees}

Well, you can tell by the way I use my walk,\\
I'm a woman's man, no time to talk.\\
Music loud and women warm\\ 
I've been kicked around since I was born.\\
And now it's all right. It's OK.\\
And you may look the other way.\\
We can try to understand the New York Time's effect on man.\\
\\
Whether you're a brother or whether you're a mother,\\
You're stayin' alive, stayin' alive.\\
Feel the city breakin' and everybody shakin',\\
And we're stayin' alive, stayin' alive.\\
Ah, ha, ha, ha, stayin' alive, stayin' alive.\\
Ah, ha, ha, ha, stayin' alive.\\
\\
Well now, I get low and I get high,\\
And if I can't get either, I really try.\\
Got the wings of heaven on my shoes.\\
I'm a dancin' man and I just can't lose.\\
You know it's all right. It's OK.\\
I'll live to see another day.\\
We can try to understand the New York Time's effect on man.\\
\\
Whether you're a brother or whether you're a mother...\\
\\
Life goin' nowhere.\\
Somebody help me.\\
Somebody help me, yeah.\\
Life goin' nowhere.\\
Somebody help me, yeah.\\
\\
Well, you can tell by the way I use my walk...\\
\\
Whether you're a brother or whether you're a mother...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Leave a Light On}{Belinda Carlisle}

Take my hand\\
Tell me what you are feeling\\
Understand\\
This is just the beginning\\
Although I have to go\\
It makes me feel like crying\\
I don't know when I'll see you again\\
\\
Darling leave a light on for me\\
I'll be there before you close the door\\
To give you all the love that you need\\
Darling leave a light on for me\\
'cause when the world takes me away\\
You are still the air that I breathe\\
\\
I can't explain\\ 
I don't know\\
Just how far I have to go\\
But darling, I'll keep the key\\
Just leave a light on for me\\
\\
Yes, I know\\
What I'm asking is crazy\\
You could go\\
Just get tired of waiting\\
But if I lose your love\\
Torn out by my desire\\
That would be the one regret of my life\\
\\
Darling leave a light on for me...\\
\\
Just like a spark lights up the dark\\
Baby that's your heart\\
Baby that's your heart\\ 
Baby that's your heart!

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2kilku}{The Time of My Life}{Bill Medley}{Jennifer Warnes}{}

Now I've had the time of my life\\
No, I never felt like this before\\
Yes, I swear it's the truth\\
And I owe it all to you\\
\\
'Cause I've had the time of my life\\
And I owe it all to you\\
\\
I've been waiting for so long\\
Now I've finally found someone\\ 
To stand by me\\

We saw the writing on the wall\\
And we felt this magical fantasy\\

Now with passion in our eyes\\
There's no way we could disguise~it~secretly\\
So we take each others hand\\
'Cause we seem to understand the urgency\\
\\
Just remember\\
You're the one thing\\
I can't get enough of\\
So I'll tell you something\\
This could be love\\
\\
Because I've had the time of my life\\
No, I never felt this way before\\
Yes, I swear it's the truth\\
And I owe it all to you\\
'Cause I've had the time of my life\\
And I've searched through every open door\\
Till I found the truth\\
And I owe it all to you\\
\\
Hey baby, oh yeah yeah yeah\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
With my body and soul\\
I want you more than you'll ever know\\
So we'll just let it go\\
Don't be afraid to lose control, no\\
\\
Yes, I know what's on your mind\\
When you say ''Stay with me tonight''\\ 
(Stay with me)\\
\\
Just remember\\
You're the one thing\\
I can't get enough of\\
So I'll tell you something\\
This could be love\\
\\
Because I've had the time of my life\\
No, I never felt this way before\\
Yes I swear it's the truth\\
And I owe it all to you\\
'Cause I've had the time of my life\\
And I've searched through every open door\\
(Never felt this way)\\
Till I found the truth\\
And I owe it all to you\\
\\
Yeah, yeah, yeah, yeah\\
Oh, whoa, oh, oh\\
\\
Now I've had the time of my life...\\
\\
I've had the time of my life...

\end{song2kilku}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{It's My Life}{bon jovi}

This ain't a song for the broken hearted.\\
No silent prayer for the faith departed.\\
I ain't gonna be just the face in the crowd,\\
You're gonna hear my voice when I shout it out loud!\\
\\
It's my life!\\
And it's now or never!\\
I ain't gonna live forever!\\
I just want to live while I'm alive!\\
It's my life!\\
My heart is like an open highway!\\
Like Frankie said, I did it my way!\\
I just wanna live while I'm alive!\\
It's my life!\\
\\
This is for the ones who stood their ground.\\
For Tommy and Gina who never backed down.\\
Tomorrow's getting harder make no mistake,\\
Luck ain't even lucky,\\
Got to make your own breaks!\\
\\
It's my life...\\
\\
Better stand tall when they're calling you out.\\
Don't bend, don't break, baby, don't back down.\\
\\
It's my life...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Holding Out for a Hero}{bonnie tyler}

Where have all the good men gone\\
And where are all the gods?\\
Where's the streetwise Hercules\\
To fight the rising odds?\\
\\
Isn't there a white knight\\ 
Upon a fiery steed?\\
Late at night I toss and I turn\\
And I dream of what I need\\
\\
I need a hero\\
I'm holding out for a hero\\
Till the end of the night\\
He's gotta be strong\\
And he's gotta be fast\\
And he's gotta be fresh from the fight\\
\\
I need a hero\\
I'm holding out for a hero\\
Till the morning light\\
He's gotta be sure\\ 
And he's gotta be soon\\
And he's gotta be larger than life\\
Larger than life\\
\\
Somewhere after midnight\\
In my wildest fantasies\\
Somewhere just beyond my reach\\
There's someone reaching back for me\\
\\
Racing on the thunder\\
And rising with the heat\\
It's gonna take a Superman\\ 
To sweep me off my feet\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
I need a hero\\
I'm holding out for a hero\\
Till the end of the night\\
He's gotta be strong\\ 
And he's gotta be fast\\
And he's gotta be fresh from the fight\\
\\
I need a hero\\
I'm holding out for a hero\\
Till the morning light\\
He's gotta be sure\\ 
And he's gotta be soon\\
And he's gotta be larger than life\\
\\
I need a hero\\
I'm holding out for a hero\\
Till the end of the night\\
\\
Upwhere the mountains\\ 
Meet the heavens above\\
Out where the lightning splits the sea\\
I could swear\\
That there's someone\\ 
Somewhere watching me\\
\\
Through the wind\\ 
And the chill\\ 
And the rain\\
And the storm\\ 
And the flood\\
I can feel his approach\\
Like a fire in my blood\\
\\
I need a hero...

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Dust in the Wind}{kansas}

I close my eyes\\
Only for a moment\\
And the moment's gone\\
All my dreams\\
Pass before my eyes\\ 
A curiosity\\
\\
Dust in the wind\\ 
All they are is dust in the wind\\
\\
Same old song\\
Just a drop of water\\
In an endless sea\\
All we do\\
Crumbles to the ground\\ 
Though we refuse to see\\
\\
Dust in the wind\\
All we are is dust in the wind\\
\\
Now, don't hang on\\
Nothing lasts forever\\ 
But the earth and sky\\
It slips away\\
And all your money\\ 
Won't another minute buy\\
\\
Dust in the wind\\
All we are is dust in the wind\\
Dust in the wind\\
Everything is dust in the wind 

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Stairway to Heaven}{Led Zeppelin}

There's a lady who's sure\\ 
All that glitters is gold\\
And she's buying a stairway to heaven.\\
When she gets there she knows,\\ 
If the stores are all closed \\
With a word she can get\\
What she came for. Ooh, ooh.\\
And she's buying\\ 
A stairway to heaven. \\
 \\
There's a sign on the wall\\
But she wants to be sure \\
'Cause you know\\
Sometimes words have two meanings. \\
In a tree by the brook,\\
There's a songbird who sings, \\
Sometimes all of our thoughts\\
Are misgiven. \\
Ooh, it makes me wonder.\\ 
Ooh, it makes me wonder.\\
 \\
There's a feeling I get\\
When I look to the west, \\
And my spirit is crying for leaving. \\
In my thoughts I have seen\\ 
Rings of smoke through the trees, \\
And the voices of those\\
Who stand looking. \\
Ooh, it makes me wonder.\\
Ooh, really makes me wonder. \\
 \\
And it's whispered that soon\\ 
If we all call the tune \\
Then the piper will lead us to reason. \\
And a new day will dawn \\
For those who stand long \\
And the forests will echo with laughter.
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
If there's a bustle in your hedgerow,\\
Don't be alarmed now, \\
It's just a spring clean for the May queen. \\
Yes, there are two paths you can go by,\\
But in the long run \\
There's still time\\
to change the road you're on. \\
And it makes me wonder. Ooh... \\
 \\
Your head is humming and it~won't~go,\\
In case you don't know, \\
The piper's calling you to join him, \\
Dear lady, can you hear the wind blow,\\
And did you know \\
Your stairway lies on the whispering wind. \\
 \\
And as we wind on down the road \\
Our shadows taller than our souls. \\
There walks a lady we all know \\
Who shines white light and wants to show \\
How everything still turns to gold. \\
And if you listen very hard \\
The tune will come to you at last. \\
When all are one and one is all \\
To be a rock and not to roll. \\
 \\
And she's buying\\
A stairway to heaven...  \\

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Hello}{Lionel Richie}

I've been alone with you inside my mind\\
And in my dreams I've kissed your lips a thousand times\\
I sometimes see you pass outside my door\\
\\
Hello!\\
Is it me you're looking for?\\
I can see it in your eyes\\
I can see it in your smile\\
You're all I've ever wanted\\
And my arms are open wide\\
'Cause you know just what to say\\
And you know just what to do\\
And I want to tell you so much\\
I love you\\
\\
I long to see the sunlight in your hair\\
And tell you time and time again how much I care\\
Sometimes I feel my heart will overflow\\
\\
Hello!\\
I've just got to let you know\\
'Cause I wonder where you are\\
And I wonder what you do\\
Are you somewhere feeling lonely?\\
Or is someone loving you?\\
Tell me how to win your heart\\
For I haven't got a clue\\
But let me start by saying\\
I love you

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Perfect Day}{Lou Reed}

Just a perfect day, drink Sangria in the park\\
And then later, when it gets dark, we go home\\
\\
Just a perfect day, feed animals in the zoo\\
Then later a movie, too, and then home\\
\\
Oh, it's such a perfect day\\
I'm glad I spend it with you\\
Oh, such a perfect day\\
You just keep me hanging on\\
You just keep me hanging on\\
\\
Just a perfect day, problems all left alone\\
Weekenders on our own -- it's such fun\\
\\
Just a perfect day, you made me forget myself\\
I thought I was someone else, someone good\\
\\
Oh, it's such a perfect day\\
I'm glad I spent it with you\\
Oh, such a perfect day\\
You just keep me hanging on\\
You just keep me hanging on\\
\\
You're going to reap just what you sow\\
You're going to reap just what you sow\\
You're going to reap just what you sow\\
You're going to reap just what you sow

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Runaway Train}{Soul Asylum}

Call you up in the middle of the night\\
Like a firefly without a light\\
You were there like a blowtorch burning\\
I was a key that could use a little turning\\
\\
So tired that I couldn't even sleep\\
So many secrets I couldn't keep\\
I promised myself I wouldn't weep\\
One more promise I couldn't keep\\
\\
It seems no one can help me now,\\
I'm in too deep; there's no way out\\
This time I have really led myself astray\\
\\
Runaway train, never going back\\
Wrong way on a one-way track\\
Seems like I should be getting somewhere\\
Somehow I'm neither here nor there\\
\\
Can you help me remember how to smile?\\
Make it somehow all seem worthwhile\\
How on earth did I get so jaded?\\
Life's mystery seems so faded\\
\\
I can go where no one else can go\\
I know what no one else knows\\
Here I am just a-drownin' in the rain\\
With a ticket for a runaway train\\
\\
And everything seems cut and dried,\\
Day and night, earth and sky,\\
Somehow I just don't believe it\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Runaway train, never going back\\
Wrong way on a one-way track\\
Seems like I should be getting somewhere\\
Somehow I'm neither here nor there\\
\\
Bought a ticket for a runaway train\\
Like a madman laughing at the rain\\
A little out of touch, a little insane\\
It's just easier than dealing with the pain\\
\\
Runaway train, never going back\\
Wrong way on a one-way track\\
Seems like I should be getting somewhere\\
Somehow I'm neither here nor there\\
\\
Runaway train, never coming back\\
Runaway train, tearing up the track\\
Runaway train, burning in my veins\\
I run away but it always seems the same

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1kilku}{Tonight I Celebrate My Love for You}{roberta flack}{Paebo Bryson}{}

Tonight I celebrate my love for you\\
It seems the natural thing to do\\
Tonight no one's gonna find us\\
We'll leave the world behind us\\
When I make love to you\\
\\
Tonight I celebrate my love for you\\
And hope that deep inside you feel it too\\
Tonight our spirits will be climbing\\
To the sky lit up with diamonds\\
When I make love to you\\ 
Tonight\\
\\
Tonight I celebrate my love for you (ooh)\\
And that midnight song is gonna come shining through\\
Tonight there'll be no distance between us\\
What I want most to do\\
Is to get close to yo\\
Tonight\\
\\
Tonight I celebrate my love for you\\
And soon this old world will seem brand new\\
Tonight we will both discover\\
How friends turn into lovers\\
When I make love to you\\
\\
Tonight I celebrate my love for you (ooh)\\
And that midnight song is gonna come shining through\\
Tonight there'll be no distance between us\\
What I want most to do\\
Is to get close to you\\
\\
Tonight I celebrate my love for you \\
Tonight

\end{song1kilku}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Eye of the Tiger}{Survivor}

Risin' up, back on the street\\
Did my time, took my chances\\
Went the distance, now I'm back on my feet\\
Just a man and his will to survive\\
\\
So many times, it happens too fast\\
You change your passion for glory\\
Don't lose your grip on the dreams of the past\\
You must fight just to keep them alive\\
\\
It's the eye of the tiger, it's the thrill of the fight\\
Risin' up to the challenge of our rival\\
And the last known survivor stalks his prey in the night\\
And he's watchin' us all with the eye of the tiger\\
\\
Face to face, out in the heat\\
Hangin' tough, stayin' hungry\\
They stack the odds 'till we take to the street\\
For we kill with the skill to survive\\
\\
It's the eye of the tiger, it's the thrill of the fight...
\\
Risin' up, straight to the top\\
Have the guts, got the glory\\
Went the distance, now I'm not gonna stop\\
Just a man and his will to survive\\
\\
It's the eye of the tiger, it's the thrill of the fight...\\
\\
The eye of the tiger...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Unbreak My Heart}{Toni Braxton}

Don't leave me in all this pain\\
Don't leave me out in the rain\\
Come back and bring back my smile\\
Come and take these tears away\\
I need your arms to hold me now\\
The nights are so unkind\\
Bring back those nights\\ 
When I held you beside me\\
\\
Unbreak my heart\\
Say you'll love me again\\
Undo this hurt you caused\\
When you walked out the door\\
And walked outta my life\\
Uncry these tears\\
I cried so many nights\\
Unbreak my heart\\
My heart\\
\\
Take back that sad word goodbye\\
Bring back the joy to my life\\
Don't leave me here with these tears\\
Come and kiss this pain away\\
I can't forget the day you left\\
Time is so unkind\\
And life is so cruel\\ 
Without you here beside me\\
\\
Unbreak my heart\\
Say you'll love me again\\
Undo this hurt you caused\\
When you walked out the door\\
And walked outta my life\\
Uncry these tears\\
I cried so many nights\\
Unbreak my heart\\
My heart
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Don't leave me in all this pain\\
Don't leave me out in the rain\\
Bring back the nights\\ 
When I held you beside me\\
\\
Unbreak my heart\\
Say you'll love me again\\
Undo this hurt you caused\\
When you walked out the door\\
And walked outta my life\\
Uncry these tears\\
I cried so many nights\\
Unbreak my heart\\
My heart\\
\\
Unbreak my heart, oh baby\\
Come back and say you love me\\
Unbreak my heart, sweet darlin'\\
Without you I just can't go on\\
Can't go on\\
\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{It's a Sin}{Pet Shop Boys}

When I look back upon my life\\
It's always with a sense of shame\\
I've always been the one to blame\\
\\
For everything I long to do\\
No matter when or where or who\\
Has one thing in common too\\
It's a, it's a, it's a, it's a sin\\
It's a sin\\
Everything I've ever done\\
Everything I ever do\\
Every place I've ever been\\
Everywhere I'm going to\\
It's a sin\\
\\
At school they taught me how to be\\
So pure in thought and word and deed\\
They didn't quite succeed\\
\\
For everything I long to do...\\
\\
Father, forgive me, I tried not~to~do~it\\
Turned over a new leaf,\\ 
Then tore right through it\\
Whatever you taught me,\\ 
I didn't believe it\\
Father, you fought me, 'cause I didn't care\\
And I still don't understand\\
\\
So I look back upon my life\\
Forever with a sense of shame\\
I've always been the one to blame\\
\\
For everything I long to do...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Don't Stop Me Now}{Queen}
Tonight I'm gonna have myself a real good time\\
I feel alive and the world turning inside out, yeah!\\
And floating around in ecstasy\\
So don't stop me now, don't stop me\\
'Cause I'm having a good time, having a good time\\
\\
I'm a shooting star leaping through the sky\\
Like a tiger defying the laws of gravity\\
I'm a racing car passing by like Lady Godiva\\
I'm gonna go go go\\
There's no stopping me\\
\\
I'm burning through the sky, yeah!\\
Two hundred degrees\\
That's why they call me Mister Fahrenheit\\
I'm trav'ling at the speed of light\\
I wanna make a supersonic man out of you\\
\\
Don't stop me now, I'm having such a good time\\
I'm having a ball, don't stop me now\\
If you wanna have a good time, just give me a call\\
Don't stop me now ('cause I'm havin' a good time)\\
Don't stop me now (yes I'm havin' a good time)\\
I don't want to stop at all\\
\\
I'm a rocket ship on my way to Mars\\
On a collision course\\
I am a satellite, I'm out of control\\
I am a sex machine ready to reload\\
Like an atom bomb about to\\
Oh oh oh oh oh explode\\
\\
I'm burning through the sky, yeah...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{American Pie}{Don McLean}
\noindent
A long, long time ago\\
I can still remember\\
How that music used to make me smile\\
And I knew if I had my chance\\
That I could make those people dance\\
And, maybe, they'd be happy for a while\\
\\
But february made me shiver\\
With every paper I'd deliver\\
Bad news on the doorstep\\
I couldn't take one more step\\
\\
I can't remember if I cried\\
When I read about his widowed bride\\
But something touched me deep inside\\
The day the music died\\
\\
So\\
Bye-bye, miss american pie\\
Drove my chevy to the levee\\
But the levee was dry\\
And them good old boys\\ 
Were drinkin' whiskey and rye\\
Singin', 'this'll be the day that I die'\\
'This'll be the day that I die'\\
\\
Did you write the book of love\\
And do you have faith in God above\\
If the Bible tells you so?\\
And do you believe in rock'n'roll\\
Can music save your mortal soul\\
And can you teach me\\ 
How to dance real slow?\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Well, I know that you're in love~with~him\\
'Cause I saw you dancin' in the gym\\
You both kicked off your shoes\\
Man, I dig those rhythm and blues\\
\\
I was a lonely teenage broncin' buck\\
With a pink carnation and a pickup truck\\
But I knew I was out of luck\\
The day the music died.\\
\\
I started singin'\\
Bye-bye, miss american pie...\\
\\
Now for ten years we've been~on~our~own\\
And moss grows fat on a rollin' stone\\
But that's not how it used to be\\
When the jester sang\\ 
For the king and queen,\\
In a coat he borrowed from james dean\\
And a voice that came from you and me\\
\\
Oh, and while the king was looking~down\\
The jester stole his thorny crown\\
The courtroom was adjourned\\
No verdict was returned\\
And while Lennon read a book of marx\\
The quartet practiced in the park\\
And we sang dirges in the dark\\
The day the music died\\
\\
We were singing\\
Bye-bye, miss american pie...\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Helter skelter in a summer swelter\\
The birds flew off with a fallout shelter\\
Eight miles high and falling fast\\
It landed foul on the grass\\
The players tried for a forward pass\\
With the jester on the sidelines in a cast\\
\\
Now the half-time air\\
Was~sweet~perfume\\
While the sergeants\\ 
Played a marching tune\\
We all got up to dance\\
Oh, but we never got the chance!\\
`Cause the players tried to take the field\\
The marching band refused to yield\\
Do you recall what was revealed\\
The day the music died?\\
\\
We started singing\\
Bye-bye, miss american pie...\\
\\
Oh, and there we were all in one place\\
A generation lost in space\\
With no time left to start again\\
So come on: jack be nimble, jack be quick!\\
Jack flash sat on a candlestick\\
Cause fire is the devil's only friend\\
\\
Oh, and as I watched him on the stage\\
My hands were clenched in fists of rage\\
No angel born in hell\\
Could break that satan's spell\\
And as the flames\\
Climbed high into the night\\
To light the sacrificial rite\\
I saw satan laughing with delight\\
The day the music died\\
\\
He was singing\\
Bye-bye, miss american pie...\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
I met a girl who sang the blues\\
And I asked her for some happy news\\
But she just smiled and turned away\\
I went down to the sacred store\\
Where I'd heard the music years before\\
But the man there said\\
The music wouldn't play\\
\\
And in the streets\\
The children~screamed\\
The lovers cried, and the poets dreamed\\
But not a word was spoken\\
The church bells all were broken\\
And the three men I admire most\\
The father, son, and the holy ghost\\
They caught the last train for the coast\\
The day the music died\\
\\
And they were singing\\
Bye-bye, miss american pie...\\
\\
They were singing\\
Bye-bye, miss american pie...

\end{song2}
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Sealed with a Kiss}{Brian Hyland}

Though we've got to say goodbye for the summer\\
Darling, I promise you this\\
I'll send you all my love\\
Everyday in a letter\\
Sealed with a kiss\\
\\
Yes it's gonna be cold, lonely summer\\
But I'll fill the emptiness\\
I'll send you all my dreams\\
Everyday in a letter\\
Sealed with a kiss\\
\\
I'll see you in the sunlight\\
I'll hear your voice everywhere\\
I'll run to tenderly hold you\\
But, Darlin', you won't be there\\
\\
I don't wanna say goodbye for the summer\\
Knowing the love we'll miss\\
Oh,let us make a pledge\\
To meet in September\\
And seal it with a kiss\\
\\
Yes it's gonna be cold, lonely summer...\\
\\
Sealed with a kiss\\
Sealed with a kiss\\
Sealed with a kiss

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Hotel California}{The Eagles}

On a dark desert highway\\ 
Cold wind in my hair\\
Warm smell of colitas \\
Rising up through the air\\
Up ahead in the distance\\ 
I saw a shimmering light\\
My head grew heavy \\
And my sight grew dim\\
I had to stop for the night\\
\\
There she stood in the doorway \\
I heard the mission bell\\
And I was thinkin' to myself\\
This could be heaven or this could be hell\\
Then she lit up a candle \\
And she showed me the way\\
There were voices down the corridor\\ 
I thought I heard them say\\
\\
Welcome to the Hotel California\\
Such a lovely place\\ 
(Such a lovely place)\\ 
Such a lovely face\\
Plenty of room at the Hotel California\\
Any time of year\\
(Any time of year)\\ 
You can find it here\\
\\
Her mind is Tiffany-twisted\\ 
She got the Mercedes Bends\\
She got a lot of pretty, pretty boys\\ 
She calls friends\\
How they dance in the courtyard\\ 
Sweet summer sweat\\
Some dance to remember\\ 
Some dance to forget
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
So I called up the Captain\\ 
'Please bring me my wine\\
He said 'We haven't had that spirit here\\ 
Since nineteen sixty-nine'\\
And still those voices are calling\\ 
From far away\\
Wake you up in the middle of the night\\ 
Just to hear them say\\
\\
Welcome to the Hotel California\\
Such a lovely place\\ 
(Such a lovely place)\\ 
Such a lovely face\\
They livin' it up at the Hotel California\\
What a nice surprise\\
(What a nice surprise)\\
Bring your alibis\\
\\
Mirrors on the ceiling\\
The pink champagne on ice\\
And she said\\
'We are all just prisoners here\\ 
Of our own device'\\
And in the masters chambers\\ 
They gathered for the feast\\
They stab it with their steely knives\\
But they just can't kill the beast\\
\\
Last thing I remember \\
I was running for the door\\
I had to find the passage\\ 
back to the place I was before\\
'Relax,' said the night man,\\ 
'We are programmed to receive\\
You can check out anytime you like\\ 
But you can never leave.'

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Enjoy the Silence}{Depeche Mode}

Words like violence\\
Break the silence\\
Come crashing in\\
Into my little world\\
Painful to me\\
Pierce right through me\\
Can’t you understand\\
Oh my little girl\\
\\
All I ever wanted\\
All I ever needed\\
Is here in my arms\\
Words are very unnecessary\\
They can only do the harm\\
\\
Vows are spoken\\
To be broken\\
Feelings are intense\\
Words are trivial\\
Pleasures remain\\
So does the pain\\
Words are meaningless\\
And forgettable\\
\\
All I ever wanted... \\
\\
Enjoy the silence

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2kilku}{All for One, All for Love}{Bryan Adams}{Rod Stewart}{sting}

When it's love you give\\
I'll be your man of good faith\\
Then in love you live\\
I'll make a stand, I won't break\\
I'll be the rock you can build on\\
Be there when you're old\\
To have and to hold\\
\\
When there's love inside\\
I swear I'll always be strong\\
Then there's a reason why\\
I'll prove to you we belong\\
I'll be the wall that protects you\\
From the wind and the rain\\
From the hurt and the pain, yeah!\\
\\
Let's make it all for one and all~for~love\\
Let the one you hold be the one you want\\
The one you need\\
'Cause when it's all for one it's one for all\\
When there's someone that should know\\
Then just let your feelings show\\
And make it all for one and all for love\\
\\
When it's love you make\\
I'll be the fire in our night\\
Then it's love you take\\
I will defend, I will fight\\
I'll be there when you need me\\
When honor's at stake\\
This vow I will make, yeah!\\
\\
That it's all for one and all for love...
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Don't lay our love to rest\\
'Cause we could stand up to the test\\
We got everything and more\\ 
Than we had planned\\
More than the rivers that run the land\\
We've got it all in our hands\\
\\
Now it's all for one and all for love...

\end{song2kilku}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{500 Miles}{The Hooters}

If you miss the train I'm on\\
You will know that I am gone\\
You can hear the whistle blow a hundred miles\\
A hundred miles, a hundred miles,\\
A hundred miles, a hundred miles\\
You can hear the whistle blow a hundred miles\\
\\
Not a shirt on my back\\
Not a penny to my name\\
And the land that I once curved is not my own\\
Lord, I'm one, Lord, I'm two,\\
Lord, I'm three, Lord, I'm four\\
Lord, I'm five hundred miles away from home\\
\\
A hundred tanks along the square\\
One man stands and stops them there\\
Someday soon the tide will turn and I'll be free\\
I'll be free, I'll be free\\
I'll come home to my country\\
Someday soon the tide will turn and I'll be free\\
\\
If you missed the train I'm on\\
You will know that I am gone\\
You can hear the whistle blow a hundred miles\\
Lord, I'm one, Lord, I'm two,\\
Lord, I'm three, Lord, I'm four\\
Lord, I'm five hundred miles away from home\\
Lord, I'm five hundred miles away from home\\
\\
I'll be free, I'll be free, I'll come home to my country\\
Lord, I'm five hundred miles away from home\\
\\
You can hear the whistle blow a hundred miles\\
Lord, I'm five hundred miles away from home

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Wind of Change}{The Scorpions}

Follow the Moskva down to Gorky Park\\
Listening to the wind of change\\
August summer night, soldiers passing by\\
Listening to the win of change\\
\\
The world is closing in and did you ever think\\
That we could be so close like brothers\\
The future's in the air, can feel it everywhere\\
I'm blowing with the wind of change\\
\\
Take me to the magic of the moment on a glory night\\
Where the children of tomorrow dream away\\
In the wind of change\\
\\
Walking down the street and distant memories\\
Are buried in the past forever\\
I follow the Moskva down to Gorky Park\\
Listening to the wind of change\\
\\
Take me to the magic of the moment on a glory night\\
Where the children of tomorrow share their dreams\\
With you and me\\
\\
Take me to the magic of the moment on a glory night\\
Where the children of tomorrow dream away\\
In the wind of change\\
\\
The wind of change blows straight into the face of time\\
Like a stormwind that will ring the freedom bell for peace of mind\\
Let your balalaika sing what my guitar wants to say\\
\\
Take me to the magic of the moment on a glory night...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{I Just Called to Say I Love You}{Stevie Wonder}

No new years's day to celebrate\\
No chocolate covered candy hearts to give away\\
No first of spring, no song to sing\\
In fact here's just another ordinary day\\
No April rain, no flowers bloom\\
No wedding Saturday within the month of June\\
But what it is, is something true\\
Made up of these three words that I must say to you\\
\\
I just called to say I love you\\
I just called to say how much I care\\
I just called to say I love you\\
And I mean it from the bottom of my heart\\
\\
No summer's high, no warm July\\
No harvest moon to light one tender August night\\
No autumn breeze, no falling leaves\\
Not even time for birds to fly to southern skies\\
No libra sun, no Halloween\\
No giving thanks to all the Christmas joy you bring\\
But what it is, though old so new\\
To fill your heart like no three words could ever do\\
\\
I just called to say I love you\\
I just called to say how much I care about you\\
I just called to say I love you\\
And I mean it from the bottom of my heart\\
\\
I just called to say I love you...\\
\\
Of my heart\\
Of my heart 

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{I Will Always Love You}{Whitney Houston}

If I should stay,\\
I would only be in your way\\
So I'll go, but I know\\
I'll think of you every step of the way\\
\\
And I will always love you\\
I will always love you\\
You, my darling, you, hmm...\\
\\
Bittersweet memories\\
that is all I'm taking with me\\
So, goodbye. Please, don't cry\\
We both know I'm not what you, you need\\
\\
And I will always love you\\
I will always love you\\
\\
I hope life treats you kind\\
And I hope you have all you've dreamed of\\
And I wish to you, joy and happiness\\
But above all this, I wish you love\\
\\
And I will always love you\\
I will always love you\\
I will always love you\\
I will always love you\\
I will always love you\\
I, I will always love you\\
\\
You, darling, I love you\\
Ooh, I'll always, I'll always love you

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Lady in Black}{Uriah Heep}

She came to me one morning\\
One lonely Sunday morning\\
Her long hair flowing\\
In the midwinter wind\\
I know not how she found me\\
For in darkness I was walking\\
And destruction lay around me\\
From a fight I could not win\\
Aaa...\\
\\
She asked me name my foe then\\
I said the need within some men\\
To fight and kill their brothers\\
Without thought of love or God\\
And I begged her give me horses\\
To trample down my enemies\\
So eager was my passion\\
To devour this waste of life\\
Aaa...\\
\\
But she wouldn't think of battle that\\
Reduces men to animals\\
So easy to begin\\
And yet impossible to end\\
For she's the mother of all men\\
Who counselled me so wisely then\\
I feared to walk alone again\\
And asked if she would stay\\
Aaa...\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Oh, lady, lend your hand outright\\
And let me rest here at your side\\
Have faith and trust in peace she said\\
And filled my heart with life\\
There is no strength in numbers\\
Have no such misconception\\
But when you need me\\
Be assured I won't be far away\\
Aaa...\\
\\
Thus having spoke she turned away\\
And though I found no words to say\\
I stood and watched until I saw\\
Her black coat disappear\\
My labour is no easier\\
But now I know I'm not alone\\
I find new heart each time\\
I think upon that windy day\\
And if one day she comes to you\\
Drink deeply from her words so wise\\
Take courage from her as your prize\\
And say hello from me\\
Aaa... 

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Shape of My Heart}{Sting}

He deals the cards as a meditation\\
And those he plays never suspect\\
He doesn't play for the money he wins\\
He don't play for respect\\
He deals the cards to find the answer\\
The secret geometry of chance\\
The hidden law of probable outcome\\
The numbers lead a dance\\
\\
I know that the spades are the swords of a soldier\\
I know that the clubs are weapons of war\\
I know that diamonds mean money for this art\\
But that's not the shape of my heart\\
\\
He may play the jack of diamonds\\
He may lay the queen of spades\\
He may conceal a king in his hand\\
While the memory of it fades\\
\\
I know that the spades are the swords of a soldier...\\
\\
That's not the shape, shape of my heart\\
\\
And if I told you that I loved you\\
You'd maybe think there's something wrong\\
I'm not a man of too many faces\\
The mask I wear is one\\
Those who speak know nothing\\
And find out to their cost\\
Like those who curse their luck in too many places\\
And those who fear are lost\\
\\
I know that the spades are the swords of a soldier...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\begin{song1}{I'm Still Standing}{elton john}

You could never know what it's like\\
Your blood like winter freezes just like ice\\
And there's a cold lonely light that shines from you\\
You'll wind up like the wreck you hide \\
Behind that mask you use.\\
\\
And did you think this fool could never win?\\
Well look at me, I'm coming back again!\\
I got a taste of love in a simple way\\
And if you need to know while I'm still standing\\
You just fade away!\\
\\
Don't you know, I'm still standing\\ 
Better than I ever did?\\
Looking like a true survivor\\ 
Feeling like a little kid!\\
I'm still standing after all this time\\
Picking up the pieces of my life without you on my mind!\\
I'm still standing, yeah, yeah, yeah.\\
I'm still standing, yeah, yeah, yeah.\\
\\
Once I never could hope to win\\
You starting down the road leaving me again\\
The threats you made were meant to cut me down\\
And if our love was just a circus\\ 
You'd be a clown by now\\
\\
Don't you know I'm still standing...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Can't Help Falling in Love}{elvis presley}

Wise men say only fools rush in\\
But I can't help falling in love with you\\
Shall I stay\\
Would it be a sin\\
If I can't help falling in love with you\\
\\
Like a river flows surely to the sea\\
Darling, so it goes\\
Some things are meant to be\\
Take my hand, take my whole life too\\
For I can't help falling in love with you\\
\\
Like a river flows surely to the sea\\
Darling, so it goes\\
Some things are meant to be\\
Take my hand, take my whole life too\\
For I can't help falling in love with you\\
\\
For I can't help falling in love with you 

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{The Final Countdown}{europe}

We're leaving together\\
But still it's farewell\\
And maybe we'll come back\\
To earth, who can tell?\\
I guess there is no one to blame\\
We're leaving ground (leaving ground)\\
Will things ever be the same again?\\
\\
It's the final countdown!\\
The final countdown\\
Ooo!\\
\\
We're heading for Venus\\
And still we stand tall\\
Cause maybe they've seen us\\
And welcome us all, yeah\\
With so many light years to go\\
And things to be found (to be found)\\
I'm sure that we'll all miss her so\\
\\
It's the final countdown!\\
The final countdown\\
Ooo...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Sweet Dreams}{Eurythmics}

Sweet dreams are made of this\\
Who am I to disagree?\\
I've traveled all world and the seven seas\\
Everybody's looking for something\\
Some of them want to use you\\
Some of them want to get used by you\\
Some of them want to abuse you\\
Some of them want to be abused\\
\\
Sweet dreams are made of this\\
Who am I to disagree?\\
I've traveled all world and the seven seas\\
Everybody's looking for something\\
\\
Hold your head up\\
Keep your head up, movin' on\\
Hold your head up, movin' on\\
Keep your head up, movin' on\\
Hold your head up, movin' on\\
Keep your head up, movin' on\\
Hold your head up, movin' on\\
Keep your head up\\
\\
Some of them want to use you\\
Some of them want to get used by you\\
Some of them want to abuse you\\
Some of them want to be abused\\
\\
Hold your head up...\\
\\
Sweet dreams are made of this...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1kilku}{Something Stupid}{Frank Sinatra}{Nancy Sinatra}{}

I know I stand in line until you think you have the time\\
To spend an evening with me\\
And if we go some place to dance\\
I know that there’s a chance you won’t be leaving with me\\
\\
Then afterwards we drop into a quiet little place\\
And have a drink or two\\
And then I go and spoil it all\\
By saying something stupid\\
Like I love you\\
\\
I can see it in your eyes\\
That you despise the same old lines\\
You heard the night before and though it’s just a line to you\\
For me it’s true and never seemed so right before\\
\\
I practice every day to find some clever lines to say\\
To make the meaning come through\\
But then I think I’ll wait until the evening gets late\\
And I’m alone with you\\
\\
The time is right, your perfume fills my head\\
The stars get red and, oh, the night’s so blue\\
And then I go and spoil it all\\
By saying something stupid\\
Like I love you\\
\\
The time is right...\\
\\
I love you, I love you, I love you

\end{song1kilku}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
\begin{song2}{Don't Cry for Me Argentina}{Madonna}

It won't be easy, you'll think it strange\\
When I try to explain how I feel\\
That I still need your love\\ 
After all that I've done\\
\\
You won't believe me\\
All you will see is a girl you once knew\\
Although she's dressed up to the nines\\
At sixes and sevens with you\\
\\
I had to let it happen, I had to change\\
Couldn't stay all my life down at heel\\
Looking out of the window,\\ 
Staying out of the sun\\
\\
So I chose freedom\\
Running around, trying everything new\\
But nothing impressed me at all\\
I never expected it to\\
\\
Don't cry for me Argentina\\
The truth is I never left you\\
All through my wild days\\
My mad existence\\
I kept my promise\\
Don't keep your distance\\
\\
And as for fortune, and as for fame\\
I never invited them in\\
Though it seemed to the world\\ 
They were all I desired\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
They are illusions\\
They're not the solutions\\
They promised~to~be\\
The answer was here all the time\\
I love you and hope you love me\\
\\
Don't cry for me Argentina\\
\\
Don't cry for me Argentina\\
The truth is I never left you\\
All through my wild days\\
My mad existence\\
I kept my promise\\
Don't keep your distance\\
\\
Have I said too much?\\
There's nothing more I can think of\\ 
To say to you\\
But all you have to do\\ 
Is look at me to know\\
That every word is true 

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Kayleigh}{Marillion}

Do you remember chalk hearts melting on a playground wall\\
Do you remember dawn escapes from moon washed college halls\\
Do you remember the cherry blossom in the market square\\
Do you remember I thought it was confetti in our hair\\
\\
By the way, didn't I break your heart?\\
Please excuse me, I never meant to break your heart\\
So sorry, I've never meant to break your heart\\
But you broke mine\\
\\
Kayleigh, is it too late to say I'm sorry?\\
And, Kayleigh, could we get it together again?\\
I just can't go on pretending that it came to a natural end\\
Kayleigh, oh, I never thought I'd miss you\\
And, Kayleigh, I thought that we'd always be friends\\
We said our love would last forever\\
So how did it come to this bitter end?\\
\\
Do you remember barefoot on the lawn with shooting stars\\
Do you remember loving on the floor in Belsize Park\\
Do you remember dancing in stilettoes in the snow\\
Do you remember you never understood I had to go\\
\\
By the way, didn't I break your heart...\\
\\
Kayleigh, I just wanna say I'm sorry\\
But, Kayleigh, I'm too scared to pick up the phone\\
To hear you've found another lover to patch up our broken home...\\
Kayleigh, I'm still trying to write that love song\\
Kayleigh, it's more important to me now you're gone\\
Maybe it will prove that we were right\\
Or it'll prove that I was wrong?

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Bang Bang (My Baby Shot Me Down)}{Nancy Sinatra}

I was five and he was six\\
We rode on horses made of sticks\\
He wore black and I wore white\\
He would always win the fight\\
\\
Bang bang, he shot me down\\
Bang bang, I hit the ground\\
Bang bang, that awful sound\\
Bang bang, my baby shot me down\\
\\
Seasons came and changed the time\\
When I grew up, I called him mine\\
He would always laugh and say\\
Remember when we used to play\\
\\
Bang bang, I shot you down\\
Bang bang, you hit the ground\\
Bang bang, that awful sound\\
Bang bang , I used to shoot you down\\
\\
Music played and people sang\\
Just for me the church bells rang\\
\\
Now he's gone, I don't know why\\
Until this day, sometimes I cry\\
He didn't even say 'Goodbye'\\
He didn't take the time to lie\\
\\
Bang bang, he shot me down\\
Bang bang, I hit the ground\\
Bang bang, that awful sound\\
Bang bang, my baby shot me down

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2kilku}{Where the Wild Roses Grow}{Kylie minogue}{Nick Cave}{}

They call me the Wild Rose\\
But my name was Elisa Day\\
Why they call me it, I do not know\\
For my name was Elisa Day\\
\\
From the first day I saw her\\
I knew she was the one\\
She stared in my eyes and smiled\\
For her lips were the color of the roses\\
They grew down the river\\ 
All bloody and wild\\
\\
When he knocked on my door\\
And entered the room\\
My trembling subsided in his sure embrace\\
He would be my first man\\
And with a careful hand\\
He wiped up the tears\\ 
That ran down my face\\
\\
They call me the Wild Rose...\\
\\
On the second day I brought her~a~flower\\
She’s more beautiful\\ 
Than any woman I've seen\\
And I said: 'Do you know\\ 
Where the wild roses grow\\
So sweet and scarlet and free?'\\
\\
On the second day he came\\ 
With a single rose\\
He said: 'Give me your loss\\ 
And your sorrow'\\
I nodded my head as I laid on the bed\\
‘If I show you the roses, will you follow?'\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
They call me the Wild Rose...\\
\\
On the third day\\ 
He took me to the river\\
He showed me the roses and we kissed\\
And the last thing I heard\\
Was a muttered word\\
As he knelt above me with a rock in~his~fist\\
\\
On the last day I took her\\ 
Where the wild roses grow\\
She lay on the bank\\ 
The wind light as a thief\\
And I kissed her goodbye\\
Said: 'All beauty must die'\\
And I knelt down\\ 
And planted a rose between her teeth\\
\\
They call me the Wild Rose...\\

\end{song2kilku}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Killing Me Softly}{Roberta Flack}

Strumming my pain with his fingers\\
Singing my life with his words\\
Killing me softly with his song\\
Killing me softly with his songs\\
Telling my whole life with his words\\
Killing me softly with his song\\
\\
I heard he sang a good song\\
I heard he had a style\\
And so I came to see him to listen for a while\\
And there he was this young boy\\
A stranger to my eyes\\
\\
Strumming my pain with his fingers...\\
\\
I felt all flushed with fever\\
Embarrassed by the crowd\\
I felt he found my letters and read each out loud\\
I prayed that he would finish\\
But he just kept right on\\
\\
Strumming my pain with his fingers...\\
\\
He sang as if he knew me \\
In all my dark despair\\
And then he looked right through me as if I wasn't there\\
And he just kept on singing\\
Singing clear and strong\\
\\
Strumming my pain with his fingers... 

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Sailing}{Rod Stewart}

I am sailing\\
I am sailing\\
Home again 'cross the sea\\
I am sailing stormy waters\\
To be near you to be free\\
\\
I am flying\\
I am flying\\ 
Like a bird 'cross the sky\\
I am flying passing high clouds\\ 
To be with you to be free\\
\\
Can you hear me?\\
Can you hear me?\\ 
Thro' the dark night far away\\
I am dying, forever crying\\ 
To be with you who can say\\
\\
Can you hear me?\\
Can you hear me?\\ 
Thro' the dark night far away\\
I am dying, forever crying\\ 
To be with you who can say\\
\\
We are sailing\\
we are sailing\\
Home again 'cross the sea\\
We are sailing stormy waters\\ 
To be near you to be free\\
\\
Oh, Lord, to be near you to be free...\\
Oh, Lord, to be near you to be free...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Friends Will Be Friends}{Queen}

Another red letter day\\
So the pound has dropped and the children are creating\\
The other half ran away\\
Taking all the cash and leaving you with the lumber\\
Got a pain in the chest\\
Doctors on strike what you need is a rest\\
\\
It's not easy love, but you've got friends you can trust\\
Friends will be friends\\
When you're in need of love they give you care and attention\\
Friends will be friends,\\
When you're through with life and all hope is lost\\
Hold out your hand cos friends will be friends\\
Right till the end\\
\\
Now it's a beautiful day\\
The postman delivered a letter from your lover\\
Only a phone call away\\
You tried to track him down but somebody stole his number\\
As a matter of fact\\
You're getting used to life without him in your way\\
\\
It's so easy now, cos you got friends you can trust\\
Friends will be friends\\
When you're in need of love they give you care and attention,\\
Friends will be friends\\
When you're through with life and all hope is lost\\
Hold out your hand cos friends will be friends\\
Right till the end \\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{I Want to Break Free}{Queen}

I want to break free\\
I want to break free\\
I want to break free from your lies\\
You're so self-satisfied, I don't need you\\
I've got to break free\\
God knows, God knows I want to break free\\
\\
I've fallen in love\\
I've fallen in love for the first time\\
And this time I know it's for real\\
I've fallen in love, yeah\\
God knows, God knows I've fallen in love\\
\\
It's strange but it's true\\
I can't get over the way you love me like you do\\
But I have to be sure\\
When I walk out that door\\
Oh, how I want to be free baby\\
Oh, how I want to be free\\
Oh, how I want to break free\\
\\
But life still goes on\\
I can't get used to living without, living without\\
Living without you by my side\\
I don't want to live alone hey\\
God knows, got to make it on my own\\
So, baby, can't you see\\
I've got to break free\\
\\
I've got to break free\\
I want to break free, yeah\\
\\
I want, I want, I want, I want to break free... \\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Somebody to Love}{Queen}

Can anybody find me somebody to love?\\
Each morning I get up I die a little\\
Can barely stand on my feet (Take a look at yourself)\\ 
Take a look in the mirror and cry\\
Lord, what you're doing to me\\
I' ve spend all my years in believing you\\
But I just can't get no relief, Lord\\
Somebody (somebody), ooh, somebody (somebody)\\
Can anybody find me somebody to love?\\
\\
I work hard (he works hard) everyday of my life\\
I work till I ache my bones\\
At the end (at the end of the day)\\
I take home my hard earned pay all on my own\\
I get down (down) on my knees (knees)\\
And I start to pray (praise the Lord)\\
'Til the tears run down from my eyes\\
Lord, somebody (somebody), ooh, somebody (please)\\
Can anybody find me somebody to love?\\
\\
(He wants help) Every day I try and I try and I try\\
But everybody wants to put me down\\
They say I'm goin' crazy\\
They say I got a lot of water in my brain\\
Got no common sense\\
I got nobody left to believe\\
Yeah, yeah, yeah, yeah...\\
Ooh, somebody (ooh, somebody)\\
Can anybody find me somebody to love?\\
(Anybody find me someone to love)\\
\\
Got no feel I got no rhythm\\
I just keep losing my beat (you just keep losing and losing)\\
I'm OK, I'm alright (he's alright, he's alright)\\
I ain't gonna face no defeat\\
I just gotta get out of this prison cell\\
One day I'm gonna be free, Lord

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{These Are the Days of Our Lives}{Queen}

Sometimes I get to feeling I was back in the old days long ago\\
When we were kids, when we were young\\
Things seemed so perfect, you know?\\
The days were endless, we were crazy, we were young\\
The sun was always shinin, we just lived for fun\\
Sometimes it seems like lately, I just don't know\\
The rest of my life's been just a show\\
\\
Those were the days of our lives\\
The bad things in life were so few\\
Those days are all gone now but one thing is true\\
When I look and I find I still love you\\
\\
You can't turn back the clock, you can't turn back the tide\\
Ain't that a shame?\\
I'd like to go back one time on a roller coaster ride\\
When life was just a game\\
No use and sitting and thinking on what you did\\
When you can lay back and enjoy it through your kids\\
Sometimes it seems like lately I just don't know\\
Better sit back and go with the flow\\
\\
'Cause these are the days of our lives\\
They've flown in the swiftness of time\\
These days are all gone now but some things remain\\
When I look and I find no change\\
\\
Those were the days of our lives, yeah\\
The bad things in life were so few\\
Those days are all gone now but one thing's still true\\
When I look and I find I still love you, I still love you\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Smooth Operator}{Sade}

He's laughing with another girl\\
And playing with another heart\\
Placing high stakes, making hearts ache\\
He's loved in seven languages\\
Diamond nights and ruby lights, high in the sky\\
Heaven help him when he falls\\
\\
Diamond life, lover boy\\
We move in space with minimum waste and maximum joy\\
City lights and business nights\\
When you require streetcar desire for higher heights\\
No place for beginners or sensitive hearts\\
When sentiment is left to chance\\
No place to be ending but somewhere to start\\
\\
No need to ask\\
He's a smooth operator, smooth operator\\
Smooth operator, smooth operator\\
Coast to coast, LA to Chicago\\
Western male\\
Across the north and south to Key Largo\\
Love for sale\\
\\
Face to face, each classic case\\
We shadow box and double cross\\
Yet need the chase\\
A license to love, insurance to hold\\
Melts all your memories and change into gold\\
His eyes are like angels but his heart is cold\\
\\
No need to ask\\
He's a smooth operator, smooth operator\\
Smooth operator, smooth operator\\
Coast to coast, LA to Chicago\\
Western male\\
Across the north and south to Key Largo\\
Love for sale

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Big Iron}{Marty Robbins}
\begin{spacing}{0.95}
To the town of Agua Fria\\
Rode a stranger one fine day\\
Hardly spoke to folks around him\\
Didn't have too much to say\\
No one dared to ask his business\\
No one dared to make a slip\\
The stranger there among them\\
Had a big iron on his hip\\
Big iron on his hip\\
\\
It was early in the morning\\
When he rode into the town\\
He came riding from the south side\\ 
Slowly lookin' all around\\
'He's an outlaw, loose and running,'\\
Came the whisper from each lip\\
'And he's here to do some business\\
With the big iron on his hip'\\
Big iron on his hip\\
\\
In this town there lived an outlaw\\
By the name of Texas Red\\
Many men had tried to take him\\ 
And that many men were dead\\
He was vicious and a killer\\
Though a youth of twenty four\\
And the notches on his pistol\\
Numbered one and nineteen more\\
One and nineteen more\\
\\
Now the stranger started talking\\
Made it plain to folks around\\
Was an Arizona ranger\\
Wouldn't be too long in town\\
He came here to take an outlaw\\
Back alive or maybe dead\\
And he said it didn't matter\\
He was after Texas Red\\
After Texas Red
\end{spacing}
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
\begin{spacing}{0.95}
Wasn't long before the story\\
Was relayed to Texas Red\\
But the outlaw didn't worry\\
Men that tried before were dead\\
Twenty men had tried to take him\\
Twenty men had made a slip\\
Twenty one would be the ranger\\
With the big iron on his hip\\
Big iron on his hip\\
\\
The morning passed so quickly\\
It was time for them to meet\\
It was twenty past eleven\\
When they walked out in the street\\
Folks were watching from the windows\\
Everybody held their breath\\
They knew this handsome ranger\\
Was about to meet his death\\
About to meet his death\\
\\
There was forty feet between them\\
When they stopped to make their play\\
And the swiftness of the ranger\\
Is still talked about today\\
Texas Red had not cleared leather\\
'Fore a bullet fairly ripped\\
And the ranger's aim was deadly\\
With the big iron on his hip\\
Big iron on his hip\\
\\
It was over in a moment\\ 
And the folks had gathered round\\
There before them lay the body\\
Of the outlaw on the ground\\
Oh, he might have went on livin'\\
But he made one fatal slip\\
When he tried to match the ranger\\
With the big iron on his hip\\
Big iron on his hip
\end{spacing}
\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Another One Bites the Dust}{Queen}

Steve walks warily down the street\\
With his brim pulled way down low\\
Ain't no sound but the sound of his feet\\
Machine guns ready to go\\
\\
Are you ready, hey, are you ready~for~this?\\
Are you hanging on the edge of your seat?\\
Out of the doorway the bullets rip\\
To the sound of the beat yeah\\
\\
Another one bites the dust\\
Another one bites the dust\\
And another one gone\\ 
And another~one~gone\\
Another one bites the dust\\
Hey, I'm gonna get you too\\
Another one bites the dust\\
\\
How do you think I'm going to~get~along\\
Without you when you're gone\\
You took me for everything that I had\\
And kicked me out on my own\\
\\
Are you happy, are you satisfied?\\
How long can you stand the heat\\
Out of the doorway the bullets rip\\
To the sound of the beat look out\\
\\
Another one bites the dust\\
Another one bites the dust\\
And another one gone\\ 
And another~one~gone\\
Another one bites the dust\\
Hey, I'm gonna get you too\\
Another one bites the dust\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Hey\\
Oh, take it\\
Bite the dust\\
Bite the dust\\
\\
Hey\\
Another one bites the dust\\
Another one bites the dust, ow\\
Another one bites the dust, he, he\\
Another one bites the dust, haaaa\\
Ooh, shoot out\\
\\
There are plenty of ways\\
That you can hurt a man\\
And bring him to the ground\\
You can beat him\\
You can cheat him\\
You can treat him bad and leave him\\
When he's down\\
But I'm ready yes I'm ready for you\\
I'm standing on my own two feet\\
Out of the doorway the bullets rip\\
Repeating to the sound of the beat\\
\\
Another one bites the dust\\
Another one bites the dust\\
And another one gone\\
And another one gone\\
Another one bites the dust, yeah\\
Hey, I'm gonna get you too\\
Another one bites the dust\\
Shoot out \\

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Bohemian Rhapsody}{Queen}
\begin{spacing}{0.95}
Is this the real life?\\
Is this just fantasy?\\
Caught in a landslide\\
No escape from reality\\
Open your eyes\\
Look up to the skies and see\\
I'm just a poor boy, I need no sympathy\\
Because I'm easy come, easy go\\
Little high, little low\\
Anyway the wind blows\\
Doesn't really matter to me, to me\\
\\
Mama just killed a man\\
Put a gun against his head\\
Pulled my trigger, now he's dead\\
Mama, life had just begun\\
But now I've gone and thrown it all away\\
Mama, ooh, didn't mean to make you cry\\
If I'm not back again this time tomorrow\\
Carry on, carry on\\
As if nothing really matters\\
\\
Too late, my time has come\\
Sends shivers down my spine\\
Body's aching all the time\\
Good bye, everybody, I've got to go\\
Gotta leave you all behind\\
And face the truth\\
\\
Mama, ooh (anyway the winds blow)\\
I don't wanna die\\
I sometimes wish I'd never been born~at~all\\
\\
I see a little silhouette of a man\\
Scaramouche, scaramouche\\
Will you do the Fandango\\
Thunderbolt and Lightning\\
Very very fright'ning me
\end{spacing}
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
\begin{spacing}{0.95}
(Galileo), Galileo, (Galileo), Galileo\\
Galileo figaro, magnifico\\
\\
I'm just a poor boy\\
And nobody loves~me\\
He's just a poor boy from a poor family\\
Spare him his life from this monstrosity\\
\\
Easy come, easy go, will you let me~go?\\
Bis-mil-lah !\\
No, we will not let you go (Let him go)\\
Bis-mil-lah !\\
We will not let you go (Let me go)\\
Bis-mil-lah !\\
We will not let you go (Let me go)\\
Will not let you go (Let me go)\\
Will not let you go (Let me go)\\
\\
Ah. No, no, no, no, no, no, no\\
(Oh mamma mia, mamma mia)\\
Mamma mia, let me go\\
Belzebub has a devil put aside for me\\
For me, for me\\
\\
So you think you can stone me\\
And spit in my eye\\
So you think you can love me\\
And leave me to die\\
Oh, baby, can't do this to me, baby\\
Just gotta get out\\
Just gotta get right outta here\\
\\
Nothing really matters\\
Anyone can see\\
Nothing really matters\\
Nothing really matters to me\\
Anyway the wind blows\\
\end{spacing}
\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{My Heart Will Go On}{Celine Dion}

Every night in my dreams\\
I see you, I feel you\\
That is how I know you go on\\
Far across the distance\\
And spaces between us\\
You have come to show you go on\\
\\
Near, far, wherever you are\\
I believe that the heart does go on\\
Once more you open the door\\
And you're here in my heart and\\
My heart will go on and on\\
\\
Love can touch us one time\\
And last for a lifetime\\
And never let go till we're gone\\
Love was when I loved you\\
One true time I hold to\\
In my life we'll always go on\\
\\
Near, far, wherever you are\\
I believe that the heart does go on\\
Once more you open the door\\
And you're here in my heart and\\
My heart will go on and on\\
\\
You're here, there's nothing I fear\\
And I know that my heart will go on\\
We'll stay forever this way\\
You are safe in my heart and\\
My heart will go on and on \\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Lost Highway}{Bon Jovi}
\begin{spacing}{0.91}
In my rearview mirror\\
My life is getting clearer\\
The sunset sighs and slowly disappears\\
These trinkets once were treasure\\
Life changes like the weather\\
You grow up, grow old, or you hit the road 'round here\\
So I drive (drive, drive)\\
Watching white lines passing by\\
With my plastic dashboard Jesus\\
Waiting there to greet us\\
\\
Hey, Hey, I finally found my way\\
Said goodbye to yesterday\\
Hit the gas, there ain't no brakes on this lost highway\\
Yeah, I'm busting loose, I'm lettin go\\
Out on this open road\\
It's independence day on this lost highway\\
Hey hey, hey hey\\
\\
Don't know where I'm going\\
But I know where I've been\\
I'm afraid of going back again\\
So I drive (drive, drive)\\
Years and miles are flying by\\
And waiting there to greet us\\
Is my plastic dashboard Jesus\\
\\
Hey, Hey, I finally found my way...\\
\\
Oh patron saint of lonely souls\\
Tell this boy which way to go\\
Guide the car, you've got the keys\\
Farewell to mediocrity\\
Kicking off the cruise control\\
And turning up the radio\\
Got just enough religion\\
And a half a tank of gas\\
Come on\\
Let's go\\
\\
I finally found my way...
\end{spacing}
\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Nothing Compares to You}{Sinead O'Connor}

It's been seven hours and fifteen days\\
Since you took your love away\\
I go out every night and sleep all day\\
Since you took your love away\\
Since you been gone I can do whatever I want\\
I can see whomever I choose\\
I can eat my dinner in a fancy restaurant\\
But nothing\\
I said nothing can take away these blues\\
\\
'Cause nothing compares\\
Nothing compares to you\\
\\
It's been so lonely without you here\\
Like a bird without a song\\
Nothing can stop these lonely tears from falling\\
Tell me, baby, where did I go wrong\\
I could put my arms around every boy I see\\
But they'd only remind me of you\\
I went to the doctor and guess what he told me\\
Guess what he told me\\
He said girl you better try to have fun\\
No matter what you do\\
But he's a fool\\
\\
'Cause nothing compares\\
Nothing compares to you\\
\\
All the flowers that you planted, mama\\
In the back yard\\
All died when you went away\\
I know that living with you baby was sometimes hard\\
But I'm willing to give it another try\\
\\
Nothing compares, nothing compares to you...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Dancing with Tears in My Eyes}{Ultravox}

Dancing with tears in my eyes\\
Weeping for the memory of a life gone by\\
Dancing with tears in my eyes\\
Living out a memory of a love that died\\
\\
It's five and I'm driving home again\\
That's hard to believe that it's my last time\\
The man on the wireless cries again\\
It's over, it's over\\
\\
Dancing with tears in my eyes...\\
\\
It's late and I'm with my love alone\\
We drink to forget the coming storm\\
We love to the sound of our favourite song\\
Over and over\\
\\
Dancing with tears in my eyes...\\
\\
It's time and we're in each others arms\\
It's time but I don't think we really care\\
\\
Dancing with tears in my eyes\\
Weeping for the memory of a life gone by\\
Dancing with tears in my eyes\\
Weeping for the memory of a life gone by\\
Dancing with tears in my eyes \\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1kilku}{Sous le Vent}{Garou}{Celine Dion}{}

Et si tu crois que j'ai eu peur\\
C'est faux\\
Je donne des vacances \`a mon coeur\\
Un peu de repos\\
Et si tu crois que j'ai eu tort\\
Attends\\
Respire un peu le souffle d'or\\
Qui me pousse en avant\\
Et\\
\\
Fais comme si j'avais pris la mer\\
J'ai sorti la grand'voile\\
Et j'ai glissé sous le vent\\
Fais comme si je quittais la terre\\
J'ai trouvé mon étoile\\
Je l'ai suivie un instant\\
Sous le vent\\
\\
Et si tu crois que c'est fini\\
Jamais\\
C'est juste une pause un répit\\
Apr\`es les dangers\\
Et si tu crois que je t'oublie\\
Écoute\\
Ouvre ton corps aux vents de la nuit\\
Ferme les yeux\\
Et\\
\\
Fais comme si j'avais pris la mer...\\
\\
Et si tu crois que c'est fini\\
Jamais (Sous le vent)\\
C'est juste une pause un répit\\
Apr\`es les dangers\\
\\
Fais comme si j'avais pris la mer...

\end{song1kilku}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Living Next Door to Alice}{Smokie}

Sally called when she got the word\\
And she said: 'I suppose you’ve heard about Alice'\\
When I rushed to the window and I looked outside\\
And I could hardly believe my eyes\\
As a big limousine rolled up into Alice’s drive\\
\\
Oh, I don’t know why she’s leaving\\
Or where she’s gonna go\\
I guess she’s got her reasons\\
But I just don’t want to know\\
’Cos for twenty-four years I’ve been living next door to Alice\\
Twenty-four years just waiting for the chance\\
To tell her how I feel and maybe get a second glance\\
Now I’ve got to get used to not living next door to Alice\\
\\
We grew up together\\
Two kids in the park\\
We carved our initials deep in the bark\\
Me and Alice\\
Now she walks through the door with her head held high\\
Just for a moment, I caught her eye\\
As a big limousine pulled slowly out of Alice’s drive\\
\\
I don’t know why she’s leaving...\\
\\
And Sally called back and asked how I felt\\
And she said: 'I know how to help -- get over Alice'\\
She said: 'Now Alice is gone but I’m still here\\
You know I’ve been waiting for twenty-four years'\\
And a big limousine disappeared\\
\\
I don’t know why she’s leaving...\\
\\
No, I’ll never get used to not living next door to Alice\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Et Si Tu N'Existais Pas}{Joe Dassin}

\begin{spacing}{0.95}
Et si tu n'existais pas\\
Dis-moi pourquoi j'existerais\\
Pour traîner dans un monde sans toi\\
Sans espoir et sans regret\\
Et si tu n'existais pas\\
J'essaierais d'inventer l'amour\\
Comme un peintre qui voit sous ses doigts\\
Naître les couleurs du jour\\
Et qui n'en revient pas\\
\\
Et si tu n'existais pas\\
Dis-moi pour qui j'existerais\\
Des passantes endormies dans mes bras\\
Que je n'aimerais jamais\\
Et si tu n'existais pas\\
Je ne serais qu'un point de plus\\
Dans ce monde qui vient et qui va\\
Je me sentirais perdu\\
J'aurais besoin de toi\\
\\
Et si tu n'existais pas\\
Dis-moi comment j'existerais\\
Je pourrais faire semblant d'\^etre moi\\
Mais je ne serais pas vrai\\
Et si tu n'existais pas\\
Je crois que je l'aurais trouvé\\
Le secret de la vie, le pourquoi\\
Simplement pour te créer\\
Et pour te regarder\\
\\
Et si tu n'existais pas\\
Dis-moi pourquoi j'existerais\\
Pour traîner dans un monde sans toi\\
Sans espoir et sans regret\\
Et si tu n'existais pas\\
J'essaierais d'inventer l'amour\\
Comme un peintre qui voit sous ses doigts\\
Naître les couleurs du jour\\
Et qui n'en revient pas 
\end{spacing}

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{One of Us}{ABBA}

They passed me by all of those great romances\\
You were, I felt, robbing me of my rightful chances\\
My picture clear, everything seemed so easy\\
And so I dealt you the blow\\
One of us had to go\\
Now it’s different\\
I want you to know\\
\\
One of us is crying\\
One of us is lying\\
In her lonely bed\\
Staring at the ceiling\\
Wishing she was somewhere else instead\\
One of us is lonely\\
One of us is only\\
Waiting for a call\\
Sorry for herself\\
Feeling stupid\\
Feeling small\\
Wishing she had never left at all\\
\\
I saw myself as a concealed attraction\\
I felt you kept me away from the heat and the action\\
Just like a child stubborn and misconceiving\\
That’s how I started the show\\
One of us had to go\\
Now I’ve changed and\\
I want you to know\\
\\
One of us is crying...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Strong Enough}{Cher}
\begin{spacing}{0.98}
I don’t need your sympathy\\
There’s nothing you can say or do for me\\
And I don’t want a miracle\\
You’ll never change for no one\\
I hear your reasons why\\
Where did you sleep last night?\\
And was she worth it, was she worth it?\\
\\
‘Cos I’m strong enough to live without you\\
Strong enough and I quit crying\\
Long enough, now I’m strong enough\\
To know you gotta go\\
There’s no more to say\\
So, save your breath\\
And then walk away\\
No matter what I hear you say\\
I’m strong enough to know you gotta go\\
\\
So, you feel misunderstood\\
Baby, have I got news for you\\
On being used I could write the book\\
What you don’t wanna hear about it\\
I've been losing sleep\\
You’ve been going cheap\\
She ain’t worth half of me, it’s true\\
Now I’m telling you\\
\\
Now I’m strong enough to live without you\\
Strong enough and I quit crying\\
Long enough, now I’m strong enough\\
To know you’ve got to go\\
\\
Come hell or waters high\\
You’ll never see me cry\\
This is our last goodbye, it’s true\\
I’m telling you...\\

Now I’m strong enough to live without you...
\end{spacing}
\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Karma Chameleon}{Culture Club}

There's a loving in your eyes all the way\\
If I listen to your lies would you say\\
I’m a man without conviction\\
I’m a man who doesn’t know\\
How to sell a contradiction\\
You come and go\\
You come and go\\
\\
Karma, karma, karma, karma, karma chameleon\\
You come and go\\
You come and go\\
Loving would be easy if your colors were like my dream\\
Red, gold and green\\
Red, gold and green\\
\\
Didn’t hear your wicked words every day\\
And you used to be so sweet I heard you say\\
That my love was an addiction\\
When we cling our love is strong\\
When you go, you’re gone forever\\
You string along\\
You string along\\
\\
Karma, karma, karma, karma, karma chameleon...\\
\\
Every day is like a survival\\
You’re my lover, not my rival\\
Every day is like a survival\\
You’re my lover, not my rival\\
\\
I’m a man without conviction\\
I’m a man who doesn’t know\\
How to sell a contradication\\
You come and go\\
You come and go\\
\\
Karma, karma, karma, karma, karma chameleon...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{I Will Survive}{Gloria Gaynor}

At first I was afraid, I was petrified\\
Kept thinkin' I could never live without you by my side\\
But then I spent so many nights thinkin' how you did me wrong\\
And I grew strong, and I learned how to get along\\
\\
And so your back, from outerspace\\
I just walked in to find you here with that sad look upon your face\\
I should've changed that stupid lock\\
I should've made you leave your key\\
If I had known for just one second you'd be back to bother me\\
\\
Go on now go, walk out the door\\
Just turn around now, 'cause you're not welcome anymore\\
Weren't you the one who tried to hurt me with goodbye\\
You think I'd crumble? You think I'd lay down and die?\\
Oh no not I, I will survive\\
Oh as long as I know how to love I know I'll stay alive\\
I've got all my life to live; I've got all my love to give\\
And I'll survive, I will survive\\
Hey, hey!\\
\\
It took all the strength I had not to fall apart\\
And trying hard to mend the pieces of my broken heart\\
And I spent oh so many nights just feeling sorry for myself\\
I used to cry, but now I hold my head up high\\
And you'll see me, somebody new\\
I'm not that chained up little person still in love with you\\
And so you felt like droppin' in and just expect me to be free\\
Now I'm savin' all my lovin' for someone who's lovin' me\\
\\
Go on now go, walk out the door...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Hit the Road, Jack}{Ray Charles}

Hit the road, Jack, and don't you come back\\
No more, no more, no more, no more\\
Hit the road, Jack, and don't you come back no more\\
What'd you say?\\
Hit the road, Jack, and don't you come back\\
No more, no more, no more, no more\\
Hit the road, Jack, and don't you come back no more\\
\\
Oh, woman, oh, woman, don't treat me so mean\\
You're the meanest old woman I have ever seen\\
\\
I guess if you say so\\
I have to pack my things and go (that's right!)\\
\\
Hit the road, Jack, and don't you come back...\\
\\
Now, baby, listen, baby, don't you treat me this a way\\
Cause I'll be back on my feet some day\\
Don't care if you do, cause it's understood\\
You ain't got no money and you just ain't no good\\
\\
Well, I guess if you say so\\
I have to pack my things and go (that's right!)\\
\\
Hit the road, Jack, and don't you come back...\\
\\
Well, oh, what you say? I didn't understand you\\
You can't mean that... Oh now, baby, please\\
What you tryin to do to me?\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{All Star}{Smash Mouth}

Somebody once told me\\
The world is gonna roll me\\
I ain't the sharpest tool in the shed\\
She was looking kind of dumb\\
With her finger and her thumb\\
In the shape, of an 'L' on her forehead\\
\\
Well, the years start coming\\
And they don't stop coming\\
Fed to the rules\\
And I hit the ground running\\
Didn't make sense not to live for fun\\
Your brain gets smart\\
But your head gets dumb\\
\\
So much to do, so much to see\\
So what's wrong\\
With taking the back streets\\
You'll never know if you don't go\\
You'll never shine if you don't glow\\
\\
Hey now, you're an All Star\\
Get your game on and go play\\
Hey now, you're a Rock Star\\
Get the show on and get paid\\
And all that glitters is gold\\
Only shooting stars break the mold\\
\\
It's a cool place\\ 
And they say it gets colder\\
You're bundled up now\\
But wait 'til you get older\\
But the meteor men beg to differ\\
Judging by the hole\\
In the satellite picture\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
The ice we skate\\
Is getting pretty thin\\
The waters getting warm\\
So you might as well swim\\
My world's on fire, how about yours?\\
That's the way I like it\\
And I never get bored\\
\\
Hey now, you're an All Star...\\
\\
Hey now, you're an All Star...\\
\\
Somebody once asked\\
'Could I spare some change for gas\\
I need to get myself away from this place'\\
I said yep, what a concept\\
I could use a little fuel myself\\
And we could all use a little change\\
\\
Well, the years start coming\\
And they don't stop coming\\
Fed to the rules\\
And I hit the ground running\\
Didn't make sense not to live for fun\\
Your brain gets smart\\
But your head gets dumb\\
\\
So much to do, so much to see\\
So what's wrong\\
With taking the back streets\\
You'll never know if you don't go\\
You'll never shine if you don't glow\\
\\
Hey now, you're an All Star...

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{I'm a Believer}{Smash Mouth}

I thought love was only true in fairy tales\\
Meant for someone else but not for me\\
Love was out to get to me\\
That's the way it seems\\
Disappointment haunted all my dreams\\
\\
And then I saw her face\\
Now I'm a believer\\
Not a trace\\
Of doubt in my mind\\
I'm in love\\
I'm a believer\\
I couldn't leave her\\
If I tried\\
\\
I thought love was more or less a given thing\\
But the more I gave the less I got, oh yeah\\
What's the use in trying\\
All you get is pain\\
When I wanted sunshine I got rain\\
\\
And then I saw her face...\\
\\
What's the use in trying\\
All you get is pain\\
When I wanted sunshine I got rain\\
\\
And then I saw her face...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Brothers in Arms}{Dire Straits}

These mist covered mountains\\
Are a home now for me\\
But my home is the lowlands\\
And always will be\\
Some day you'll return to\\
Your valleys and your farms\\
And you'll no longer burn\\
To be brothers in arms\\
\\
Through these fields of destruction\\
Baptism of fire\\
I've witnessed your suffering\\
As the battles raged higher\\
And though they did hurt me so bad\\
In the fear and alarm\\
You did not desert me\\
My brothers in arms\\
\\
There's so many different worlds\\
So many different suns\\
And we have just one world\\
But we live in different ones\\
\\
Now the sun's gone to hell\\
And the moon's riding high\\
Let me bid you farewell\\
Every man has to die\\
But it's written in the starlight\\
And every line on your palm\\
We're fools to make war\\
On our brothers in arms \\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{We Didn't Start the Fire}{Billy Joel}
('49)\\
Harry Truman, Doris Day\\
Red China, Johnnie Ray\\
South Pacific, Walter Winchell\\
Joe DiMaggio\\
\\
('50)\\
Joe McCarthy, Richard Nixon\\
Studebaker, television\\
North Korea, South Korea\\
Marilyn Monroe\\
\\
('51)\\
Rosenbergs, H-bomb\\
Sugar Ray, Panmunjom\\
Brando, 'The King and I'\\
And 'The Catcher in the Rye'\\
\\
('52)\\
Eisenhower, vaccine\\
England's got a new queen\\
Marciano, Liberace\\
Santayana goodbye\\
\\
We didn't start the fire\\
It was always burning\\
Since the world's been turning\\
We didn't start the fire\\
No we didn't light it\\
But we tried to fight it\\
\\
('53)\\
Joseph Stalin, Malenkov\\
Nasser and Prokofiev\\
Rockefeller, Campanella\\
Communist Bloc\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
('54)\\
Roy Cohn, Juan Peron\\
Toscanini, dacron\\
Dien Bien Phu falls\\
'Rock Around the Clock\\
\\
('55)\\
Einstein, James Dean\\
Brooklyn's got a winning team\\
Davy Crockett, Peter Pan\\
Elvis Presley, Disneyland\\
\\
('56)\\
Bardot, Budapest\\
Alabama, Krushchev\\
Princess Grace, 'Peyton Place'\\
Trouble in the Suez\\
\\
We didn't start the fire...\\
\\
('57)\\
Little Rock, Pasternak\\
Mickey Mantle, Kerouac\\
Sputnik, Chou En-Lai\\
'Bridge on the River Kwai'\\
\\
('58)\\
Lebanon, Charlse de Gaulle\\
California baseball\\
Starkweather, homicide\\
Children of thalidomide\\
\\
('59)\\
Buddy Holly, 'Ben Hur'\\
Space monkey, Mafia\\
Hula hoops, Castro\\
Edsel is a no-go\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
('60)\\
U-2, Syngman Rhee\\
Payola and Kennedy\\
Chubby Checker, 'Psycho'\\
Belgians in the Congo\\
\\
We didn't start the fire...\\
\\
('61)\\
Hemingway, Eichmann\\
'Stranger in a Strange Land'\\
Dylan, Berlin\\
Bay of Pigs invasion\\
\\
('62)\\
'Lawrence of Arabia'\\
British Beatlemania\\
Ole Miss, John Glenn\\
Liston beats Patterson\\
\\
('63)\\
Pope Paul, Malcolm X\\
British politician sex\\
JFK blown away\\
What else do I have to say\\
\\
We didn't start the fire...\\
\\
('64-'89)\\
Birth control, Ho Chi Minh\\
Richard Nixon back again\\
Moonshot, Woodstock\\
Watergate, punk rock\\
\\
Begin, Reagan, Palestine\\
Terror on the airline\\
Ayatollah's in Iran\\
Russians in Afghanistan\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
'Wheel of Fortune', Sally Ride\\
Heavy metal, suicide\\
Foreign debts, homeless vets\\
AIDS, crack, Bernie Goetz\\
\\
Hypodermics on the shores\\
China's under martial law\\
Rock and roller cola wars\\
I can't take it anymore\\
\\
We didn't start the fire...

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{High on Emotion}{Chris De Burgh}

Oh, my heart is spinning like a wheel\\
Only she can see the way that I fell\\
Eyes are holding right across the room\\
High explosion coming out of the blue\\
\\
Well, here we go again\\
Living in a world that others cannot share\\
Yea, here we go again\\
We are moving from a spark to a flame\\
\\
I am high, high, high on emotion\\
High, high, high again\\
High, high, high on emotion\\
your love will find the way\\
\\
Oh, my heart is burning like a fire\\
Closer now and she is breathing desire\\
Take my hand and give it all your light\\
Take command I am your rhythm tonight\\
\\
Well, here we go again...\\
\\
I am high, high, high on emotion...\\
\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{I Just Died in Your Arms}{Cutting Crew}

Oh I, I just died in your arms tonight\\
It must have been something you said\\
I just died in your arms tonight\\
\\
I keep looking for something I can't get\\
Broken hearts lie all around me\\
And I don't see an easy way to get out of this\\
Her diary sits by the bedside table\\
The curtains are closed, the cat's in the cradle\\
Who would have thought that a boy like me could come to this\\
\\
Oh I, I just died in your arms tonight\\
It must have been something you said\\
I just died in your arms tonight\\
Oh I, I just died in your arms tonight\\
It must have been some kind of kiss\\
I should have walked away, I should have walked away\\
\\
Is there any just cause for feeling like this?\\
On the surface I'm a name on a list\\
I've tried to be discreet, but then I'd blow it again\\
I've lost and found, it's my final mistake\\
She's loving by proxy, no give and all take\\
Cause I've been thrilled to fantasy one too many times\\
\\
Oh I, I just died in your arms tonight...\\
\\
It was a long hot night\\
And she made it easy, she made it feel right\\
But now it's over, the moment has gone\\
I followed my hands not my head, I know I was wrong\\
\\
Oh I, I just died in your arms tonight...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Money for Nothing}{Dire Straits}

Now look at them yo-yo's, that's the way you do it\\
You play the guitar on the MTV\\
That ain't workin', that's the way you do it\\
Money for nothin' and chicks for free\\
Now that ain't workin', that's the way you do it\\
Lemme tell, ya, them guys ain't dumb\\
Maybe get a blister on your little finger\\
Maybe get a blister on your thumb\\
\\
We gotta install microwave ovens\\
Custom kitchen deliveries\\
We gotta move these refrigerators\\
We gotta move these colour TV's\\
\\
See the little faggot with the earring and the makeup\\
Yeah, buddy, that's his own hair\\
That little faggot got his own jet airplane\\
That little faggot he's a millionaire\\
\\
We gotta install microwave ovens...\\
\\
I shoulda learned to play the guitar\\
I shoulda learned to play them drums\\
Look at that mama, she got it stickin' in the camera\\
Man, we could have some fun\\
And he's up there, what's that? Hawaiian noises?\\
Bangin' on the bongoes like a chimpanzee\\
That ain't workin', that's the way you do it\\
Get your money for nothin' get your chicks for free\\
\\
We gotta install microwave ovens...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Pride (In the Name of Love)}{U2}

One man come in the name of love\\
One man come and go\\
One man come he to justify\\
One man to overthrow\\
\\
In the name of love\\
What more in the name of love\\
In the name of love\\
What more in the name of love\\
\\
One man caught on a barbed wire fence\\
One man he resist\\
One man washed on an empty beach\\
One man betrayed with a kiss\\
\\
In the name of love\\
What more in the name of love\\
In the name of love\\
What more in the name of love\\
\\
Early morning, April 4\\
Shot rings out in the Memphis sky\\
Free at last they’re took your life\\
They’re could not take your pride\\
\\
In the name of love\\
What more in the name of love\\
In the name of love\\
What more in the name of love\\
In the name of love\\
What more in the name of love\\
In the name of love\\
What more in the name of love\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Sultans of Swing}{Dire Straits}

You get a shiver in the dark\\
It's raining in the park but meantime\\
South of the river you stop and you hold everything\\
A band is blowing Dixie double four time\\
You feel alright when you hear the music ring\\
\\
And now you step inside but you don't see too many faces\\
Coming in out of the rain to hear the jazz go down\\
Competition in other places\\
Oh, but the horns they blowing that sound\\
Way on down south, way on down south London town\\
\\
You check out Guitar George, he knows all the chords\\
But he's strictly rhythm he doesn't wanna make it cry or sing\\
Yes and an old guitar is all he can afford\\
When he gets up under the lights to play his thing\\
\\
And Harry doesn't mind, if he doesn't make the scene\\
He's got a daytime job, he's doing alright\\
He can play the honky tonk like anything\\
Saving it up for Friday night\\
With the Sultans, with the Sultans of Swing\\
\\
And a crowd of young boys, they're fooling around in the corner\\
Drunk and dressed in their best brown baggies and their platform soles\\
They don't give a damn about any trumpet playing band\\
It ain't what they call rock and roll\\
And the Sultans, yeah, the Sultans play Creole\\
Creole\\
\\
And then the man he steps right up to the microphone\\
And says at last just as the time bell rings\\
'Goodnight, now it's time to go home'\\
And he makes it fast with one more thing\\
'We are the Sultans, we are the Sultans of Swing'\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Young Turks}{Rod Stewart}

Billy left his home with a dollar in his pocket and a head full of dreams\\
He said somehow, some way, it's gotta get better than this\\
Patti packed her bags, left a note for her mom, she was just seventeen\\
There were tears in her eyes, when she kissed her little sister on goodbye\\
\\
They held each other tight as they drove on through the night\\
They were so~exited\\
We got just one shot of life, lets take it while were still not afraid\\
Because life is so brief and time is a thief when you're undecided\\
And like a fistful of sand, it can slip right through your hands\\
\\
Young hearts be free tonight\\
Time is on your side\\
Don't let them put you down, dont let 'em push you around\\
Don't let 'em ever change your point of view\\
\\
Paradise was closed so they headed for the coast in a blissful manner\\
They took a tworoom apartment that was jumping every night of the week\\
Happiness was found in each others arms as expected, yeah\\
Billy pierced his ears, drove a pickup like a lunatic, ooo-oh!\\
\\
Young hearts be free tonight...\\
\\
Billy wrote a letter back home to pattis parents tryin to explain\\
He said were both real sorry that it had to turn out this way\\
But there ain't no point in talking when there is nobody listning\\
So we just ran away\\
Patti gave birth to a ten pound baby boy, oh yeah!\\
\\
Young hearts be free tonight...\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Does Your Mother Know}{ABBA}

You're so hot, teasing me\\
So you're blue but I can't take a chance on a chick like you\\
That's something I couldn't do\\
There's that look in your eyes\\
I can read in your face that your feelings are driving you wild\\
Ah, but girl you're only a child\\
\\
Well, I can dance with you honey\\
If you think it's funny\\
Does your mother know that you're out?\\
And I can chat with you baby\\
Flirt a little maybe\\
Does your mother know that you're out?\\
\\
Take it easy (take it easy)\\
Better slow down girl\\
That's no way to go\\
Does your mother know?\\
Take it easy (take it easy)\\
Try to cool it girl\\
Take it nice and slow\\
Does your mother know?\\
\\
I can see what you want\\
But you seem pretty young to be searching for that kind of fun\\
So maybe I'm not the one\\
Now you're so cute, I like your style\\
And I know what you mean\\
When you give me a flash of that smile (smile)\\
But girl you're only a child\\
\\
Well, I can dance with you honey...\\
\\
Take it easy (take it easy)...\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Thank You for the Music}{ABBA}
\begin{spacing}{0.98}
I’m nothing special\\
In fact, I’m a bit of a bore\\
If I tell a joke\\
You’ve probably heard it before\\
But I have a talent\\
A wonderful thing\\
’Cause everyone listens\\
When I start to sing\\
I’m so grateful and proud\\
All I want is to sing it out loud\\
So I say\\
\\
Thank you for the music, the songs I’m singing\\
Thanks for all the joy they’re bringing\\
Who can live without it? I ask in all honesty\\
What would life be? Without a song or a dance what are we?\\
So I say thank you for the music, for giving it to me\\
\\
Mother says I was\\
A dancer before I could walk\\
She says I began\\
To sing long before I could talk\\
And I’ve often wondered\\
How did it all start\\
Who found out that nothing\\
Can capture a heart\\
Like a melody can\\
Well, whoever it was, I’m a fan\\
So I say\\
\\
Thank you for the music, the songs I’m singing...\\
\\
I’ve been so lucky\\
I am the girl with golden hair\\
I wanna sing it out to everybody\\
What a joy, what a life, what a chance\\
\\
Thank you for the music, the songs I’m singing...
\end{spacing}
\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Waterloo}{ABBA}

My, my, at Waterloo Napoleon did surrender\\
Oh yeah, and I have met my destiny in quite a similar way\\
The history book on the shelf\\
Is always repeating itself\\
\\
Waterloo -- I was defeated, you won the war\\
Waterloo -- promise to love you for ever more\\
Waterloo -- couldn’t escape if I wanted to\\
Waterloo -- knowing my fate is to be with you\\
Oh, oh, oh, oh!\\
Waterloo -- finally facing my Waterloo\\
\\
My, my, I tried to hold you back but you were stronger\\
Oh yeah, and now it seems my only chance is skipping up the fight\\
And how could I ever refuse?\\
I feel like I win when I lose\\
\\
Waterloo -- I was defeated, you won the war\\
Waterloo -- promise to love you for ever more\\
Waterloo -- couldn’t escape if I wanted to\\
Waterloo -- knowing my fate is to be with you\\
Oh, oh, oh, oh!\\
Waterloo -- finally facing my Waterloo\\
\\
So how could I ever refuse?\\
I feel like I win when I lose\\
\\
Waterloo -- couldn’t escape if I wanted to\\
Waterloo -- knowing my fate is to be with you\\
Oh, oh, oh, oh!
Waterloo -- finally facing my Waterloo\\
Waterloo -- knowing my fate is to be with you\\
Oh, oh, oh, oh!\\
Waterloo -- finally facing my Waterloo\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Forever Young}{Alphaville}
\begin{spacing}{0.98}
Let's dance in style, let's dance for a while\\
Heaven can wait, we're only watching the skies\\
Hoping for the best but expecting the worst\\
Are you going drop the bomb or not?\\
\\
Let us die young, let us live forever\\
We don't have the power but we never say never\\
Sitting in a sandpit, life is a short trip\\
The music's for the sad men\\
\\
Can you imagine when this race is won?\\
Turn our golden faces into the sun\\
Praising our leaders we're getting in tune\\
The music's played by the, the madman\\
\\
Forever young, I want to be forever young\\
Do you really want to live forever?\\
Forever or never\\
Forever young, I want to be forever young\\
Do you really want to live forever?\\
Forever young\\
\\
Some are like water, some are like the heat\\
Some are a melody and some are the beat\\
Sooner or later they all will be gone\\
Why don't they stay young?\\
\\
It's so hard to get old without a cause\\
I don't want to perish like a fading horse\\
Youth's like diamonds in the sun\\
And diamonds are forever\\
\\
So many adventures couldn't happen today\\
So many songs we forgot to play\\
So many dreams are swinging out of the blue\\
We let them come true\\
\\
Forever young, I want to be forever young...
\end{spacing}
\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Rasputin}{Boney M}

There lived a certain man\\
In Russia long ago\\
He was big and strong\\
In his eyes a flaming glow\\
Most people looked at him\\
With terror and with fear\\
But to Moscow chicks\\
He was such a lovely dear\\
He could preach the Bible like a preacher\\
Full of ecstasy and fire\\
But he also was the kind of teacher\\
Women would desire\\
\\
Ra, Ra, Rasputin\\
Lover of the Russian queen\\
There was a cat that really was gone\\
Ra, Ra, Rasputin\\
Russia's greatest love machine\\
It was a shame how he carried on\\
\\
He ruled the Russian land\\
And never mind the tsar\\
But the kasachok he danced\\
Really wunderbar\\
In all affairs of state\\
He was the man to please\\
But he was real great\\
When he had a girl to squeeze\\
For the queen he was no wheeler dealer\\
Though she heard the things he'd done\\
She believed he was a holy healer\\
Who would heal her son\\
\\
Ra, Ra, Rasputin...\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
(But when his drinking\\
And lusting and his hunger\\
For power became known\\
To more and more people\\
The demands to do something\\
About this outrageous\\
Man became louder and louder...)\\
\\
This man just got to go!\\
Declared his enemies\\
But the ladies begged\\
Don't you try to do it, please\\
No doubt this Rasputin\\
Had lots of hidden charms\\
Though he was a brute\\
They just fell into his arms\\
Then one night\\
Some men of higher~standing\\
Set a trap, they're not to blame\\
Come to visit us they kept demanding\\
And he really came\\
\\
Ra, Ra, Rasputin\\
Lover of the Russian queen\\
They put some poison into his wine\\
Ra, Ra, Rasputin\\
Russia's greatest love machine\\
He drank it all and he said 'I feel fine'\\
\\
Ra, Ra, Rasputin\\
Lover of the Russian queen\\
They didn't quit, they wanted his head\\
Ra, Ra, Rasputin\\
Russia's greatest love machine\\
And so they shot him till he was dead

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Miracle of Love}{Eurythmics}

How many sorrows\\
Do you try to hide\\
In a world of illusion\\
That's covering your mind?\\
I'll show you something good\\
\\
Oh, I'll show you something good\\
When you open your mind\\
You'll discover the sign\\
That there's something\\
You're longing to find\\
\\
The miracle of love\\
Will take away your pain\\
When the miracle of love\\
Comes your way again\\
\\
Cruel is the night\\
That covers up your fears\\
Tender is the one\\
That wipes away your tears\\
There must be a bitter breeze\\
To make you sting so viciously\\
They say the greatest coward\\
Can hurt the most ferociously\\
\\
But I'll show you something good\\
Oh, I'll show you something good\\
If you open your heart\\
You can make a new start\\
When your crumbling world falls apart\\
\\
The miracle of love...\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Total Eclipse of the Heart}{Bonnie Tyler}
\begin{spacing}{0.9}
Turn around\\
Every now and then\\
I get a little bit lonely\\
And you're never coming 'round\\
\\
Turn around\\
Every now and then\\
I get a little bit~tired\\
Of listening to the sound of my tears\\
\\
Turn around\\
Every now and then\\
I get a little bit~nervous\\
That the best of all the years have gone by\\
\\
Turn around\\
Every now and then\\
I get a little bit terrified\\
And then I see the look in your eyes\\
\\
Turn around bright eyes\\
Every now and then I fall apart\\
Turn around bright eyes\\
Every now and then I fall apart\\
\\
Turn around\\
Every now and then\\
I get a little bit restless\\
And I dream of something wild\\
\\
Turn around\\
Every now and then\\
I get a little bit helpless\\
And I'm lying like a child in your arms\\
\\
Turn around\\
Every now and then\\
I get a little bit angry\\
And I know I've got to get out and cry\\
\end{spacing}
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
\begin{spacing}{0.95}
Turn around\\
Every now and then\\
I get a little bit terrified\\
But then I see the look in your eyes\\
\\
Turn around bright eyes...\\
\\
And I need you now tonight\\
And I need you more than ever\\
And if you only hold me tight\\
We'll be holding on forever\\
And we'll only be making it right\\
'Cause we'll never be wrong\\
\\
Together we can take it\\
To the end of the line\\
Your love is like a shadow\\
On me all of the time\\
I don't know what to do\\
And I'm always in the dark\\
We're living in a powder keg\\
And giving off sparks\\
\\
I really need you tonight\\
Forever's gonna start tonight\\
Forever's gonna start tonight\\
\\
Once upon a time I was falling in~love\\
But now I'm only falling apart\\
There's nothing I can do\\
A total eclipse of the heart\\
\\
Once upon a time\\
There was light in my~life\\
But now there's only love in the dark\\
Nothing I can say\\
A total eclipse of the heart\\
\\
Turn around bright eyes...
\end{spacing}
\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Everything I Do (I Do It for You)}{Bryan Adams}

Look into my eyes, you will see\\
What you mean to me\\
Search your heart, search your soul\\
And when you find me there, you will search no more\\
\\
Don't tell me it's not worth tryin' for\\
Can't tell me it's not worth dyin' for\\
You know it's true\\
Everything I do, I do it for you\\
\\
Look into your heart, you will find\\
There's nothin' there to hide\\
Take me as I am, take my life\\
I would give it all, I would sacrifice\\
\\
Don't tell me it's not worth fightin' for\\
I can't help it, there's nothin' I want more\\
You know it's true\\
Everything I do, I do it for you\\
\\
There's no love like your love\\
And no other could give more love\\
There's nowhere unless you're there\\
All the time, all the way\\
\\
Look into your heart, babe\\
\\
Oh, you can't tell me it's not worth tryin' for\\
I can't help it, there's nothin' I want more\\
Yeah, I would fight for you, I'd lie for you\\
Walk the wire for you, yeah, I'd die for you\\
\\
You know it's true\\
Everything I do, oh, I do it for you\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Time After Time}{Cyndi Lauper}

Lying in my bed I hear the clock tick and think of you\\
Caught up in circles, confusion is nothing new\\
Flashback warm nights almost left behind suitcase of memories\\
Time after...\\
\\
Sometimes you picture me I'm walking too far ahead\\
You're calling to me I can't hear what you've said\\
\\
Then you say go slow I fall behind\\
The second hand unwinds\\
\\
If you're lost you can look and you will find me\\
Time after time\\
If you fall I will catch you, I'll be waiting\\
Time after time\\
If you're lost you can look and you will find me\\
Time after time\\
If you fall I will catch you, I'll be waiting\\
Time after time\\
\\
After my picture fades and darkness has turned to grey\\
Watching trough windows you're wondering if I'm okay\\
Secrets stolen from deep inside\\
The drum beats out of time\\
\\
If you're lost you can look and you will find me...\\
\\
You say go slow I fall behind\\
The second hand unwinds\\
\\
If you're lost you can look and you will find me...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{True Colors}{Cyndi Lauper}

You with the sad eyes\\
Don't be discouraged\\
Oh, I realize\\
It's hard to take courage\\
In a world full of people\\
You can lose sight of it all\\
And the darkness inside you\\
Can make you feel so small\\
\\
But I see your true colors\\
Shining through\\
I see your true colors\\
And that's why I love you\\
So don't be afraid to let them show\\
Your true colors\\
True colors are beautiful\\
Like a rainbow\\
\\
Show me a smile then\\
Don't be unhappy, can't remember when\\
I last saw you laughing\\
If this world makes you crazy\\
And you've taken all you can bear\\
You call me up\\
Because you know I'll be there\\
\\
And I'll see your true colors...\\
\\
(Can't remember when I last saw you laughing)\\
If this world makes you crazy\\
And you've taken all you can bear\\
You call me up\\
Because you know I'll be there\\
\\
And I'll see your true colors...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Voyage, Voyage}{Desireless}

Au dessus des vieux volcans\\
Glisse des ailes sous les tapis du vent\\
Voyage, voyage\\
Eternellement\\
De nuages en marécages\\
De vent d'Espagne en pluie d'équateur\\
Voyage, voyage\\
Vole dans les hauteurs\\
Au dessus des capitales\\
Des idées fatales\\
Regarde l'océan\\
\\
Voyage, voyage\\
Plus loin que la nuit et le jour\\
Voyage\\
Dans l'espace inoui de l'amour\\
Voyage, voyage\\
Sur l'eau sacrée d'un fleuve indien\\
Voyage\\
Et jamais ne reviens\\
\\
Sur le Gange ou l'Amazone\\
Chez les blacks, chez les sikhs, chez les jaunes\\
Voyage, voyage\\
Dans tout le royaume\\
Sur les dunes du Sahara\\
Des îles Fidji au Fujiyama\\
Voyage, voyage\\
Ne t'arretes pas\\
Au dessus des barbelés\\
Des coeurs bombardés\\
Regarde l'océan\\
\\
Voyage, voyage...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Sacrifice}{Elton John}

It's a human sign\\
When things go wrong\\
When the scent of her lingers\\
And temptation's strong\\
\\
Into the boundary\\
Of each married man\\
Sweet deceit comes calling\\
and negativity lands\\
\\
Cold, cold heart\\
Hard done by you\\
Some things look better, baby\\
Just passing through\\
\\
And it's no sacrifice\\
just a simple word\\
It's two hearts living\\
In two several worlds\\
But it's no sacrifice\\
No sacrifice\\
It's no sacrifice at all\\
\\
Mutual misunderstanding\\
After the fact\\
Sensitivity builds a prison\\
In the final act\\
\\
We lose direction\\
No stone unturned\\
No tears to damn you\\
When jealousy burns\\
\\
Cold, cold heart...\\
\\
And it's no sacrifice...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Blue Suede Shoes}{Elvis Presley}

Well, it's one for the money, two for the show\\
Three to get ready, now go cat go\\
But don't you step on my blue suede shoes\\
Well, you can do anything\\
But lay off of my blue suede shoes\\
\\
You can knock me down, step on my face\\
Slander my name all over the place\\
Do anything that you wanna do\\
But, uh, uh, honey lay off them shoes\\
And don't you step on my blue suede shoes\\
You can do anythinga but lay off of my blue suede shoes\\
\\
Well, you can burn my house, steal my car\\
Drink my liquor from an old fruit jar\\
Do anything that you wanna do\\
But, uh, uh, honey lay off of my shoes\\
And don't you step on my blue suede shoes\\
Well, you can do anything\\
but lay off of my blue suede shoes\\
\\
Well, it's one for the money, two for the show\\
Three to get ready, now go, go, go\\
But don't you step on my blue suede shoes\\
Well, you can do anything but lay off my blue suede shoes\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{The Real Slim Shady}{Eminem}
\begin{spacing}{0.9}
May I have your attention please?\\
May I have your attention please?\\
Will the real Slim Shady please stand up?\\
I repeat, will the real Slim Shady please stand up?\\
We're gonna have a problem here\\
\\
Y'all act like you never seen a white person before\\
Jaws all on the floor like Pam, like Tommy just burst in the door\\
And started whoopin her ass worse than before\\
They first were divorce, throwin her over furniture (Ahh!)\\
It's the return of the 'Ah, wait, no way, you're kidding,\\
He didn't just say what I think he did, did he?'\\
And Dr. Dre said... nothing you idiots!\\
Dr. Dre's dead, he's locked in my basement! (Ha-ha!)\\
Feminist women love Eminem\\
'Slim Shady, I'm sick of him\\
Look at him, walkin around grabbin his you-know-what\\
Flippin the you-know-who,' 'Yeah, but he's so cute though!'\\
Yeah, I probably got a couple of screws up in my head loose\\
But no worse, than what's goin on in your parents' bedrooms\\
Sometimes, I wanna get on TV and just let loose, but can't\\
But it's cool for Tom Green to hump a dead moose\\
'My bum is on your lips, my bum is on your lips'\\
And if I'm lucky, you might just give it a little kiss\\
And that's the message that we deliver to little kids\\
And expect them not to know what a woman's clitoris is\\
Of course, they gonna know what intercourse is\\
By the time they hit fourth grade\\
They got the Discovery Channel don't they?\\
'We ain't nothing but mammals' Well, some of us cannibals\\
Who cut other people open like cantaloupes\\
But if we can hump dead animals and antelopes\\
Then there's no reason that a man and another man can't elope\\
But if you feel like I feel, I got the antidote\\
Women wave your pantyhose, sing the chorus and it goes\\
\\
I'm Slim Shady, yes, I'm the real Shady\\
All you other Slim Shadys are just imitating\\
So won't the real Slim Shady please stand up\\
Please stand up, please stand up?
\end{spacing}
\end{varwidth}
\end{center}
\newpage
\begin{center}
\begin{varwidth}{\columnwidth}
\begin{spacing}{0.9}
Will Smith don't gotta cuss in his raps to sell his records\\
Well, I do, so fuck him and fuck you too!\\
You think I give a damn about a Grammy?\\
Half of you critics can't even stomach me, let alone stand me\\
'But Slim, what if you win, wouldn't it be weird?'\\
Why? So you guys could just lie to get me here?\\
So you can, sit me here next to Britney Spears?\\
Shit, Christina Aguilera better switch me chairs\\
So I can sit next to Carson Daly and Fred Durst\\
And hear 'em argue over who she gave head to first\\
You little bitch, put me on blast on MTV\\
'Yeah, he's cute, but I think he's married to Kim, hee-hee!'\\
I should download her audio on MP3\\
And show the whole world how you gave Eminem VD\\
I'm sick of you little girl and boy groups, all you do is annoy me\\
So I have been sent here to destroy you\\
And there's a million of us just like me\\
Who cuss like me, who just don't give a fuck like me\\
Who dress like me, walk, talk and act like me\\
And just might be the next best thing but not quite me!\\
\\
I'm Slim Shady, yes, I'm the real Shady...
\\
I'm like a head trip to listen to, cause I'm only givin you\\
Things you joke about with your friends inside your living room\\
The only difference is I got the balls to say it\\
In front of y'all and I don't gotta be false or sugarcoated at all\\
I just get on the mic and spit it\\
And whether you like to admit it I just shit it\\
Better than ninety percent of you rappers out can\\
Then you wonder how can kids eat up these albums like valiums\\
It's funny, cause at the rate I'm goin when I'm thirty\\
I'll be the only person in the nursin home flirting\\
Pinchin nurses asses when I'm jackin off with Jergens\\
And I'm jerkin but this whole bag of Viagra isn't working\\
And every single person is a Slim Shady lurkin\\
He could be workin at Burger King, spittin on your onion rings\\
Or in the parkin lot, circling\\
Screaming 'I don't give a fuck!'\\
With his windows down and his system up\\
So, will the real Shady please stand up?\\
And put one of those fingers on each hand up?\\
And be proud to be outta your mind and outta control\\
And one more time, loud as you can, how does it go?\\
\\
I'm Slim Shady, yes, I'm the real Shady...
\end{spacing}
\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Lemon Tree}{Fool's Garden}

I'm sitting here, in a boring room\\
It's just another rainy sunday afternoon\\
I'm wasting my time, I got nothing to do\\
I'm hanging around, I'm waiting for you\\
But nothing ever happens and I wonder\\
\\
I'm driving around in my car\\
I'm driving too fast, I'm driving too far\\
I'd like to change my point of view\\
I feel so lonely, I'm waiting for you\\
But nothing ever happens and I wonder\\
\\
I wonder how, I wonder why\\
Yesterday you told me 'bout the blue blue sky\\
And all that I can see\\
Is just a yellow lemon tree\\
I'm turning my head up and down\\
I'm turning, turning, turning, turning, turning around\\
And all that I can see\\
Is just another lemon tree\\
\\
I'm sitting here, I miss the power\\
I'd like to go out, taking a shower\\
But there's heavy cloud inside my head\\
I feel so tired, put myself into bed\\
Where nothing ever happens and I wonder\\
\\
Isolation is not good for me\\
Isolation, I don't want to sit on a lemon tree\\
\\
I'm steppin' around in a desert of joy\\
Baby, anyhow I'll get another toy\\
And everything will happen and you'll wonder\\
\\
I wonder how, I wonder why...\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Got My Mind Set on You}{George Harrison}

I got my mind set on you, I got my mind set on you\\
I got my mind set on you, I got my mind set on you\\
\\
But it's gonna take money\\
A whole lotta spending money\\
It's gonne take plenty of money\\
To do it right, child\\
It's gonna take time\\
A whole lot of precious time\\
It's gonna take patience and time, ummm\\
To do it, to do it, to do it, to do it, to do it\\
To do it right, child\\
\\
I got my mind set on you, I got my mind set on you\\
I got my mind set on you, I got my mind set on you\\
\\
And this time I know it's for real\\
The feelings that I feel\\
I know if I put my mind to it\\
I know that I really can do it\\
\\
I got my mind set on you, set on you\\
I got my mind set on you, set on you\\
\\
But it's gonna take money...\\
\\
I got my mind set on you, I got my mind set on you\\
I got my mind set on you, I got my mind set on you\\
\\
And this time I know it's for real\\
The feelings that I feel\\
I know if I put my mind to it\\
I know that I really can do it\\
\\
But it's gonna take money...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Wake Me Up When September Ends}{Green Day}

Summer has come and passed\\
The innocent can never last\\
Wake me up when September ends\\
Like my father’s come to pass\\
Seven years has gone so fast\\
Wake me up when September ends\\
\\
Here comes the rain again\\
Falling from the stars\\
Drenched in my pain again\\
Becoming who we are\\
As my memory rests\\
But never forgets what I lost\\
Wake me up when september ends\\
\\
Summer has come and passed\\
The innocent can never last\\
Wake me up when September ends\\
Ring out the bells again\\
Like we did when spring began\\
Wake me up when September ends\\
\\
Here comes the rain again\\
Falling from the stars\\
Drenched in my pain again\\
Becoming who we are\\
As my memory rests\\
But never forgets what I lost\\
Wake me up when September ends\\
\\
Summer has come and passed\\
The innocent can never last\\
Wake me up when September ends\\
Like my father’s come to pass\\
Twenty years has gone so fast\\
Wake me up when September ends x3\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{American Idiot}{Green Day}

Don’t want to be an American Idiot\\
Don’t want a nation under the new mania\\
Can you hear the sound of hysteria?\\
The subliminal mind fuck America\\
\\
Welcome to a new kind of tension\\
All across the alienation\\
Where everything isn’t meant to be ok\\
Television dreams of tomorrow\\
We’re not the ones meant to follow\\
For that’s enough to argue\\
\\
Maybe I am the faggot America\\
I’m not a part of a redneck agenda\\
Now everybody do the propaganda\\
And sing along to the age of paranoia\\
\\
Welcome to a new kind of tension...\\
\\
Don’t want to be an American Idiot\\
One nation controlled by the media\\
Information age of hysteria\\
Calling out to Idiot America\\
\\
Welcome to a new kind of tension...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Boulevard of Broken Dreams}{Green Day}

I walk a lonely road\\
The only one that I have ever known\\
Don't know where it goes\\
But it's home to me and I walk alone\\
\\
I walk this empty street\\
On the Boulevard of Broken Dreams\\
Where the city sleeps\\
And I'm the only one and I walk alone\\
\\
I walk alone, I walk alone\\
I walk alone, I walk alone\\
\\
My shadow's the only one that walks beside me\\
My shallow heart's the only thing that's beating\\
Sometimes I wish someone out there will find me\\
Till then I walk alone\\
\\
I'm walking down the line\\
That divides me somewhere in my mind\\
On the borderline\\
Of the edge and where I walk alone\\
\\
Read between the lines\\
Of what's fucked up and everything's alright\\
Check my vital signs to know I'm still alive\\
And I walk alone\\
\\
I walk alone, I walk alone\\
I walk alone, I walk alone\\
\\
My shadow's the only one that walks beside me...\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song2}{Hallelujah}{Rufus Wainwright}

I've heard there was a secret chord\\
That David played\\
And it pleased the Lord\\
But you don't really care for music\\
Do~you?\\
It goes like this\\
The fourth, the fifth\\
The minor fall, the major lift\\
The baffled king composing\\
Hallelujah\\
\\
Hallelujah, hallelujah\\
Hallelujah, hallelujah\\
\\
Your faith was strong\\
But you needed proof\\
You saw her bathing on the roof\\
Her beauty and the moonlight\\
Overthrew you\\
She tied you to a kitchen chair\\
She broke your throne\\
And she cut your hair\\
And from your lips she drew the\\
Hallelujah\\
\\
Hallelujah, hallelujah\\
Hallelujah, hallelujah\\
\\
Maybe I have been here before\\
I know this room, I've walked this floor\\
I used to live alone before I knew you\\
I've seen your flag on the marble arch\\
Love is not a victory march\\
It's a cold and it's a broken\\
Hallelujah\\
\end{varwidth}
\end{center}
\columnbreak
\begin{center}
\begin{varwidth}{\columnwidth}
Hallelujah, hallelujah\\
Hallelujah, hallelujah\\
\\
There was a time you let me know\\
What's real and going on below\\
But now you never show it to me, do you?\\
And remember when I moved in you?\\
The holy dark was moving too\\
And every breath we drew was\\
Hallelujah\\
\\
Hallelujah, hallelujah\\
Hallelujah, hallelujah\\
\\
Maybe there's a god above\\
And all I ever learned from love\\
Was how to shoot at someone\\
Who outdrew~you\\
And it's not a cry you can hear at night\\
It's not somebody who's seen the light\\
It's a cold and it's a broken\\
Hallelujah\\
\\
Hallelujah, hallelujah\\
Hallelujah, hallelujah\\
Hallelujah, hallelujah\\
Hallelujah, hallelujah\\

\end{song2}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{What a Wonderful World}{Louis Armstrong}

I see trees of green\\
Red roses too\\
I see them bloom\\
For me and you\\
And I think to myself\\
What a wonderful world!\\
\\
I see skies of blue\\
And clouds of white\\
The bright blessed day\\
The dark sacred night\\
And I think to myself\\
What a wonderful world!\\
\\
The colours of the rainbow\\
So pretty in the sky\\
Are also on the faces\\
Of people going by\\
I see friends shaking hands\\
Sayin': 'How do you do?'\\
They're really sayin'\\
'I love you'\\
\\
I hear babies cryin'\\
I watch them grow\\
They'll learn much more\\
Than I'll ever know\\
And I think to myself\\
What a wonderful world!\\
\\
Yes\\
I think to myself\\
What a wonderful world! \\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Beds Are Burning}{Midnight Oil}

Out where the river broke\\
The blood wood and the desert oak\\
Holden wrecks and boiling diesels\\
Steam in fourty-five degrees\\
\\
The time has come to say fair's fair\\
To pay the rent, to pay our share\\
The time has come a fact's a fact\\
It belongs to them, let's give it back\\
\\
How could we dance when our earth is turning\\
How do we sleep while our beds are burning\\
How could we dance when our earth is turning\\
How do we sleep while our beds are burning\\
\\
The time has come to say fair's fair\\
To pay the rent, now to pay our share\\
\\
Four wheels scare the cockatoos\\
From Kintore East to Yuendemu\\
The western desert lives and breathes\\
In fourty-five degrees\\
\\
The time has come to say fair's fair...\\
\\
How could we dance when our earth is turning...\\
\\
The time has come to say fair's fair\\
To pay the rent, now, to pay our share\\
The time has come, a fact's a fact\\
It belongs to them, we're gonna give it back\\
\\
How could we dance when our earth is turning...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{She's Like the Wind}{Patrick Swayze}

She's like the wind through my tree\\
She rides the night next to me\\
She leads me through moonlight\\
Only to burn me with the sun\\
She's taken my heart\\
But she doesn't know what she's done\\
\\
Feel her breath on my face\\
Her body close to me\\
Can't look in her eyes\\
She's out of my league\\
Just a fool to believe\\
I have anything she needs\\
She's like the wind\\
\\
I look in the mirror and all I see\\
Is a young old man with only a dream\\
Am I just fooling myself\\
That she'll stop the pain\\
Living without her\\
I'd go insane\\
\\
Feel her breath on my face...\\
\\
Feel your breath on my face\\
Your body close to me\\
Can't look in your eyes\\
You're out of my league\\
Just a fool to believe\\
She's like the wind\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Hope of Deliverance}{Paul McCartney}

I will allways be hoping, hoping\\
You will allways be holding, holding\\
My heart in your hand\\
I will understand\\
\\
I will understand, some day, one day\\
You will understand, always, always\\
From now until then\\
\\
When it will be right, I don't know\\
What it will be like, I don't know\\
We live in hope of deliverence\\
From the darkness that surrounds us\\
\\
Hope of deliverence, hope of deliverence\\
Hope of deliverence from the darkness\\
That surrounds us\\
\\
And I wouldn't mind knowing, knowing\\
That you wouldn't mind going, going\\
Along with my plan\\
\\
When it will be right, I don't know...\\
\\
Hope of deliverence, hope of deliverence...\\

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{The Show Must Go On}{Queen}
\begin{spacing}{0.95}
Empty spaces, what are we living for?\\
Abandoned places, I guess we know the score?\\
On and on\\
Does anybody know what we are looking for?\\
\\
Another hero, another mindless crime\\
Behind the curtain in the pantomime\\
Hold the line!\\
Does anybody want to take it anymore\\
\\
Show must go on! Show must go on! Yeah!\\
Inside my heart is breaking\\
My make-up may be flaking\\
But my smile still stays on\\
\\
Whatever happens, I'll leave it all to chance\\
Another heartache, another failed romance\\
On and on\\
Does anybody know what we are living for?\\
\\
I guess I'm learning, I must be warmer now\\
I'll soon be turning, round the corner now\\
Outside the dawn is breaking\\
But inside in the dark I'm aching to be free\\
\\
Show must go on...\\
\\
My soul is painted like the wings of butterflies\\
Fairytales of yesterday will grow but never die\\
I can fly, my friends!\\
Show must go on! Show must go on!\\
\\
I'll face it with a grin\\
I'm never giving in on with the show!\\
\\
I'll top the bill, I'll overkill \\
I have to find the will to carry on\\
(On with the show, with the) show!\\
Show must go on! 
\end{spacing}
\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{We Are the Champions}{Queen}

I've paid my dues\\
Time after time\\
I've done my sentence\\
But committed no crime\\
And bad mistakes\\
I've made a few\\
I've had my share of sand\\
Kicked in my face\\
But I've come through\\
And I need to go on and on, and on, and on\\
\\
We are the champions, my friend\\
And we'll keep on fighting till the end\\
We are the champions\\
We are the champions\\
No time for losers\\
'Cause we are the champions of the world\\
\\
I've taken my bows\\
And my curtain calls\\
You've brought me fame and fortune\\
And everything that goes with it\\
I thank you all\\
But it's been no bed of roses no pleasure cruise\\
I consider it a challenge before the whole human race\\
And I ain't gonna lose\\
And I need to go on and on, and on, and on\\
\\
We are the champions, my friend...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Everybody Hurts}{R.E.M.}

When the day is long and the night\\
The night is yours alone\\
When you're sure you've had enough of this life, well, hang on\\
Don't let yourself go\\
'Cause everybody cries and everybody hurts sometimes\\
\\
Sometimes everything is wrong\\
Now it's time to sing along\\
\\
When your day is night alone (hold on, hold on)\\
If you feel like letting go (hold on)\\
When you think you've had too much of this life, well, hang on\\
\\
'Cause everybody hurts\\
Take comfort in your friends\\
Everybody hurts\\
Don't throw your hand\\
Oh, no. Don't throw your hand\\
If you feel like you're alone\\
No, no, no, you are not alone\\
\\
If you're on your own in this life\\
The days and nights are long\\
When you think you've had too much of this life to hang on\\
\\
Well, everybody hurts sometimes\\
Everybody cries\\
And everybody hurts sometimes\\
And everybody hurts sometimes\\
So, hold on, hold on\\
Hold on, hold on\\
Hold on, hold on\\
Hold on, hold on

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{song1}{Everybody Was Kung Fu Fighting}{The Village People}

Everybody was kung-fu fighting\\
Those cats were fast as lightning\\
In fact it was a little bit frightning\\
But they fought with expert timing\\
\\
They were funky China men\\
From funky Chinatown\\
They were chopping them up\\
And they were chopping them down\\
It's an ancient Chineese art\\
And everybody knew their part\\
From a feint into a slip\\
And kicking from the hip\\
\\
Everybody was kung-fu fighting...\\
\\
There was funky Billy Chin \\
And little Sammy Chung\\
He said 'here comes the big boss\\
Lets get it on'\\
We took a bow and made a stand\\
Started swinging with the hand\\
The sudden motion made me skip \\
Now we're into a brand knew trip\\
\\
Everybody was kung-fu fighting...

\end{song1}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% KONIEC WPISYWANIA PIOSENEK %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
